#!/usr/bin/env python3
"""BrotherMode cross-runtime adapters: emit per-runtime instruction files.

WHY THIS EXISTS
  BrotherMode's engine is a handful of Python files driven from a shell. Nothing
  in bm_store.py, bm_threads.py, bm_learn.py or bm_telemetry.py is specific to
  Claude Code. What IS specific to Claude Code is the wiring: the hooks, and the
  file the runtime reads to learn the law. Every other coding runtime has its own
  instruction file convention and its own hook story, and a founder who works in
  two runtimes should not have to hand transcribe the law into each one and then
  watch the copies drift.

  So this file generates them. One registry of runtimes, one renderer, one
  command. Regenerating is cheap, which is the point: a generated file that
  drifts is a bug the gate catches, a hand written one is a bug nobody sees.

WHAT THIS FILE REFUSES TO DO
  It does not guess. Every destination path in the registry below was read off
  the runtime vendor's own documentation page on the date recorded beside it, and
  the URL travels with the fact: into the generated file's header, and into
  docs/RUNTIMES.md. A convention that could not be verified ships marked GENERIC
  with the reason attached, rather than shipping as a confident path that sends
  the founder's law into a file nothing reads.

  It also does not overwrite anything the founder owns. Emission writes into a
  STAGING directory (docs/runtimes by default, which is COMMITTED on purpose so
  the adapter files are readable on the repository page) plus the capability
  table, and prints an install map. AGENTS.md at a repository root is frequently
  a file with real content in it already; a generator that clobbers it would be
  worse than no generator. Every target is checked before anything is written:
  a file that exists and does NOT carry this generator's marker line is treated
  as founder owned, and the whole emit refuses rather than writing part of it.
  --out moves the capability table too, so a redirected emit touches nothing
  outside the directory the founder named.

THE HONEST LIMIT, STATED ONCE HERE AND AGAIN IN EVERY FILE IT WRITES
  Two different questions get confused constantly, so they are kept apart:
    1. does this runtime have hook points at all
    2. do BROTHERMODE's hooks run there
  Question 1 has a verified answer per runtime. Question 2 has exactly one
  verified yes, Claude Code, because bm_fence_hook.py and bm_telemetry.py's hook
  targets parse Claude Code's hook JSON contract (documented in docs/HOOKS.md).
  Another runtime having a PreToolUse event does NOT mean it hands that event the
  same JSON shape. Until somebody runs the adapter against the real runtime and
  records the payload, the correct entry is "hook points exist, BrotherMode hook
  compatibility unverified", and that is what the table says.

  The retrieval and store commands are the opposite case: they are ordinary
  processes that read stdin and write stdout, so they work in any runtime that
  can run a shell command, and that claim needs no per runtime verification.

Python 3.9, standard library only. No network, no subprocess. The verification
this file's registry depends on happened OUT OF BAND, by a human or an agent
opening the vendor page and recording the URL and the date; this module never
fetches anything at runtime, and it never could.

No em or en dashes anywhere in this file, its comments, or its output.
"""

import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# The date every URL in the registry below was actually opened and read. It is
# rendered into every generated file so a reader can judge for themselves how
# stale the claim is, instead of trusting a document with no date on it.
VERIFIED_ON = "2026-07-29"

GENERATED_MARKER = "GENERATED BY BrotherMode tools/bm_runtimes.py"

# Where emitted adapters land by default. docs/runtimes is COMMITTED on purpose
# rather than hidden under .brothermode: this is a public product, and somebody
# deciding whether BrotherMode fits their Codex or Qwen setup should be able to
# read the exact adapter file on the repository page without cloning and running
# anything. It also means `check` can gate the committed copies against the
# registry in the normal suite, which is what stops the capability table and the
# adapter files from drifting apart.
DEFAULT_STAGING = os.path.join("docs", "runtimes")


# ---------------------------------------------------------------------------
# The BrotherMode surface that works in ANY runtime with a shell.
#
# Every command name below is a real dispatch key in the named module. It is not
# a remembered flag and not an invented one: test_bm_runtimes.py asserts each
# string appears as a quoted dispatch key in that module's source, so a renamed
# command breaks the gate instead of shipping a generated file that tells five
# runtimes to run something that does not exist.
#
# FLAGS ARE DELIBERATELY ABSENT. The generated files tell the agent to run the
# command with --help and read the real flags off the tool. That is one extra
# step for the agent and it removes the entire class of "the instruction file
# taught the agent a flag that was never there".
# ---------------------------------------------------------------------------
CLI_SURFACE = (
    ("bm_store.py",
     "the transactional store: ownership, fences, handover digests",
     ("init", "claim", "verify", "dashboard", "checkpoint", "decide",
      "complete", "park", "resume", "adopt", "dump")),
    ("bm_threads.py",
     "thread mode: one persistent thread per feature, one chief coordinating",
     ("on", "off", "start", "checkpoint", "send", "dashboard", "park",
      "resume", "complete", "adopt", "decide", "recommend")),
    ("bm_learn.py",
     "correction learning: capture, approval, and retrieval of founder rules",
     ("lookup", "apply", "rules", "candidates", "approve", "why", "verify")),
    ("bm_telemetry.py",
     "session telemetry and the nine metric scorecard",
     ("scorecard", "intent", "fence-lint", "check-update", "review-mark")),
)


# ---------------------------------------------------------------------------
# THE RUNTIME REGISTRY
#
# Fields:
#   key            the name the CLI takes
#   title          human name, used in headings
#   staging_name   the file this generator writes into the staging directory.
#                  Deliberately prefixed by runtime key: two runtimes can share
#                  a DESTINATION (several read AGENTS.md) and staging must not
#                  collide.
#   install_file   the bare path the founder installs to, for the one line
#                  capability table cell. It exists as its OWN field because the
#                  first version derived it by splitting destinations[0] on ".",
#                  which truncated at the dot inside the filename: Copilot's cell
#                  rendered EMPTY and two others lost their extension. A prose
#                  sentence is not a path and must never be parsed as one.
#                  _check_registry ties it back to the verified prose so it
#                  cannot drift into an invented path.
#   destinations   where the founder copies the file to, verbatim from the
#                  vendor page named in `sources`. Prose, possibly several
#                  sentences: rendered whole, never sliced.
#   verified       True only when a vendor page was opened and the destination
#                  read off it. False renders a GENERIC banner plus `reason`.
#   reason         why it could not be verified. Required when verified is False.
#   sources        ((label, url), ...) pages actually opened on VERIFIED_ON
#   hooks          None when no hook mechanism was found on the pages opened,
#                  else dict(config, events, source)
#   notes          honest caveats specific to this runtime
# ---------------------------------------------------------------------------
RUNTIMES = (
    {
        "key": "generic",
        "title": "Generic AGENTS.md",
        "staging_name": "generic.AGENTS.md",
        "install_file": "AGENTS.md",
        "destinations": ("AGENTS.md at the repository root. In a monorepo, a "
                         "nested AGENTS.md may sit in each subproject and the "
                         "closest one to the edited file wins.",),
        "verified": True,
        "reason": "",
        "sources": (("AGENTS.md, the open format", "https://agents.md"),),
        "hooks": None,
        "notes": (
            "This is the widest reach for the least work. The format page lists "
            "OpenAI Codex, GitHub Copilot, Gemini CLI, Cursor, VS Code, Zed, "
            "Aider, goose, Devin, Windsurf and JetBrains Junie among the tools "
            "that read it, so one file covers runtimes this registry does not "
            "name individually.",
            "AGENTS.md is a plain instruction file. It carries no hook "
            "mechanism of its own, in any runtime.",
        ),
    },
    {
        "key": "codex",
        "title": "OpenAI Codex CLI",
        "staging_name": "codex.AGENTS.md",
        "install_file": "AGENTS.md",
        "destinations": (
            "AGENTS.md, starting at the project root (typically the git root) "
            "and in any directory down to the working directory.",
            "AGENTS.override.md takes priority over AGENTS.md in the same "
            "directory.",
            "Global scope: the Codex home directory, which defaults to "
            "~/.codex and follows CODEX_HOME when that is set.",
        ),
        "verified": True,
        "reason": "",
        "sources": ((
            "Custom instructions with AGENTS.md",
            "https://learn.chatgpt.com/docs/agent-configuration/agents-md"),),
        "hooks": {
            "config": ("~/.codex/hooks.json or an inline [hooks] table in "
                       "~/.codex/config.toml for user scope; "
                       "<repo>/.codex/hooks.json or an inline [hooks] table in "
                       "<repo>/.codex/config.toml for project scope."),
            "events": ("SessionStart", "SessionEnd", "PreToolUse", "PostToolUse",
                       "PermissionRequest", "PreCompact", "PostCompact",
                       "UserPromptSubmit", "SubagentStart", "SubagentStop",
                       "Stop"),
            "source": ("Codex hooks", "https://learn.chatgpt.com/docs/hooks"),
        },
        "notes": (
            "Codex builds its instruction chain once when it starts, so editing "
            "an AGENTS.md mid session does not reload it.",
            "The event NAMES overlap heavily with Claude Code's, which is "
            "exactly the trap: an overlapping name is not a compatible payload. "
            "See the compatibility note below before wiring any hook.",
        ),
    },
    {
        "key": "copilot",
        "title": "GitHub Copilot",
        "staging_name": "copilot.copilot-instructions.md",
        "install_file": ".github/copilot-instructions.md",
        "destinations": (
            ".github/copilot-instructions.md at the repository root, for "
            "repository wide instructions.",
            "Copilot also reads AGENTS.md files stored within the repository, "
            "nearest file first. Support for AGENTS.md outside the workspace "
            "root is off by default.",
            "Copilot CLI additionally reads $HOME/.copilot/copilot-instructions.md.",
        ),
        "verified": True,
        "reason": "",
        "sources": ((
            "Adding repository custom instructions in your IDE",
            "https://docs.github.com/en/copilot/how-tos/configure-custom-instructions-in-your-ide/add-repository-instructions-in-your-ide"),
            ("Adding custom instructions for GitHub Copilot CLI",
             "https://docs.github.com/en/copilot/how-tos/copilot-cli/customize-copilot/add-custom-instructions")),
        "hooks": None,
        "notes": (
            "Neither page opened describes any hook or lifecycle event "
            "mechanism. Instructions take effect on save and are added to "
            "requests; nothing runs an external program on an event.",
            "That makes Copilot a retrieval and CLI runtime for BrotherMode. "
            "The fence is advisory here: BrotherMode can tell Copilot the law "
            "and Copilot can run the store commands, but no PreToolUse gate "
            "stands in front of a write, so the one writer promise is a "
            "coordination ledger in this runtime, not a boundary.",
        ),
    },
    {
        "key": "antigravity",
        "title": "Google Antigravity",
        "staging_name": "antigravity.brothermode.md",
        "install_file": ".agents/rules/brothermode.md",
        "destinations": (
            "A markdown rules file inside the .agents/rules folder in the "
            "workspace or git root. Older installs use .agent/rules. The "
            "FOLDER is what the documentation specifies; the filename is "
            "yours, and brothermode.md is this generator's choice.",
            "Global rules live at ~/.gemini/GEMINI.md.",
        ),
        "verified": True,
        "reason": "",
        "sources": ((
            "Antigravity docs, Rules and Workflows",
            "https://antigravity.google/docs/rules-workflows"),),
        "hooks": {
            "config": ("hooks.json in the customization directory: .agents/ in "
                       "the workspace, or ~/.gemini/config/ globally."),
            "events": ("PreToolUse", "PostToolUse", "PreInvocation",
                       "PostInvocation", "Stop"),
            "source": ("Antigravity docs, Hooks",
                       "https://antigravity.google/docs/hooks"),
        },
        "notes": (
            "The rules page opened here does NOT mention AGENTS.md. Third "
            "party guides claim Antigravity reads it; that claim is "
            "UNVERIFIED and this generator does not act on it. Install the "
            "rules file at the documented path rather than relying on it.",
            "Third party guides also report a 12000 character cap per rules "
            "file. The official page opened does not state a limit, so the cap "
            "is UNVERIFIED. This generator keeps the Antigravity file short "
            "regardless, because a short file is correct either way.",
            "Antigravity enables auto continue by default in recent versions, "
            "which means long unattended chains. Explicit deny rules matter "
            "more here than in a runtime that pauses.",
        ),
    },
    {
        "key": "qwen",
        "title": "Qwen Code",
        "staging_name": "qwen.QWEN.md",
        "install_file": "QWEN.md",
        "destinations": (
            "QWEN.md at the project root, shared with the team through version "
            "control.",
            "~/.qwen/QWEN.md for instructions that follow you across projects.",
            ".qwen/QWEN.local.md for project specific personal instructions.",
            "Qwen also reads an existing AGENTS.md if the repository has one.",
        ),
        "verified": True,
        "reason": "",
        "sources": ((
            "Qwen Code docs, Memory",
            "https://qwenlm.github.io/qwen-code-docs/en/users/features/memory/"),),
        "hooks": {
            "config": ("a hooks object in Qwen Code settings, typically "
                       ".qwen/settings.json. disableAllHooks true at the top "
                       "level switches every hook off."),
            "events": ("SessionStart", "SessionEnd", "PreToolUse", "PostToolUse",
                       "PostToolUseFailure", "UserPromptSubmit", "PreCompact",
                       "PostCompact", "SubagentStart", "SubagentStop", "Stop",
                       "StopFailure", "Notification", "PermissionRequest",
                       "TodoCreated", "TodoCompleted"),
            "source": ("Qwen Code docs, Hooks",
                       "https://qwenlm.github.io/qwen-code-docs/en/users/features/hooks/"),
        },
        "notes": (
            "The context filename is configurable through the context.fileName "
            "setting, so a project that has changed it needs the file under "
            "that name instead.",
            "Qwen's hook event list is the closest match to Claude Code's of "
            "any runtime here, including SessionStart and SessionEnd, which are "
            "the two BrotherMode's telemetry actually targets. That makes it "
            "the most promising adapter target and still not a verified one.",
        ),
    },
    {
        "key": "iflow",
        "title": "iFlow CLI",
        "staging_name": "iflow.IFLOW.md",
        "install_file": "IFLOW.md",
        "destinations": (
            "IFLOW.md at the project root.",
            "~/.iflow/IFLOW.md for global scope.",
            "IFLOW.md inside a subdirectory, which takes priority over the "
            "project root file for work in that subdirectory.",
        ),
        "verified": True,
        "reason": "",
        "sources": ((
            "iFlow CLI configuration, Memory",
            "https://platform.iflow.cn/en/cli/configuration/iflow"),),
        "hooks": None,
        "notes": (
            "contextFileName is configurable and accepts a list, so a project "
            "can point iFlow at AGENTS.md instead of, or alongside, IFLOW.md.",
            "The page opened describes memory COMMANDS (/init, /memory show, "
            "/memory add, /memory refresh) and no hook mechanism. A slash "
            "command the founder types is not a hook point: nothing runs an "
            "external program on a tool call or at session end, so the "
            "autosave, the fence gate and the session telemetry have nowhere "
            "to attach in this runtime.",
        ),
    },
)


# ---------------------------------------------------------------------------
# Output funnel. Everything this module prints goes through these two, for the
# same reason bm_learn.py funnels its output: one place to audit.
# ---------------------------------------------------------------------------
def _out(msg=""):
    sys.stdout.write(msg + "\n")


def _err(msg):
    sys.stderr.write(msg + "\n")


def _load_bm_store():
    """Load bm_store.py by PATH, the same shape bm_telemetry.py and bm_learn.py
    use: this command runs from arbitrary working directories and must not
    depend on cwd being on sys.path. Only resolve_root is used, so a failure
    here degrades to an explicit refusal rather than a wrong root."""
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            "bm_store_for_runtimes", os.path.join(HERE, "bm_store.py"))
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod, None
    except Exception as e:
        return None, repr(e)


def resolve_project_root(explicit=None):
    """Return (root, source) or (None, reason). Never guesses cwd silently."""
    if explicit:
        p = os.path.realpath(os.path.expanduser(explicit))
        if not os.path.isdir(p):
            return None, "no such directory: %s" % p
        return p, "explicit"
    mod, err = _load_bm_store()
    if mod is None:
        return None, ("could not load bm_store.py to resolve the project root "
                      "(%s); pass --root explicitly" % err)
    root, src = mod.resolve_root()
    if not root:
        return None, ("nothing anchors a BrotherMode project here. Run "
                      "bm_store.py init, set BROTHERMODE_ROOT, or pass --root")
    return root, src


def tools_reference(root):
    """How the generated files should spell the path to the tools directory.

    Relative when the tools live inside the project (the normal installed
    shape, and it survives the repository being moved or cloned elsewhere),
    absolute otherwise. Either way it is a REAL path computed here, not a
    placeholder the founder has to remember to substitute."""
    real_root = os.path.realpath(root)
    real_tools = os.path.realpath(HERE)
    if real_tools == real_root or real_tools.startswith(real_root + os.sep):
        return os.path.relpath(real_tools, real_root)
    return real_tools


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------
def _hook_compat_block(rt):
    """The paragraph that keeps 'has hook points' apart from 'BrotherMode's
    hooks run here'. It is rendered for EVERY runtime, including the ones with
    no hooks at all, because the confusion is the same in both directions."""
    lines = []
    lines.append("## Hooks in this runtime")
    lines.append("")
    h = rt["hooks"]
    if h is None:
        lines.append("This runtime has NO hook mechanism on the documentation "
                     "opened for it. That is a capability statement, not a "
                     "complaint: it means the autosave, the pre write fence "
                     "gate and the session end telemetry have nowhere to "
                     "attach here, and BrotherMode in this runtime is the "
                     "instruction file plus the commands above.")
        lines.append("")
        lines.append("The fence is therefore ADVISORY here. The store still "
                     "refuses an overlapping claim, so two sessions cannot "
                     "both be recorded as owning a file. What is missing is "
                     "the gate that stands in front of an actual write, so an "
                     "agent that ignores the law can still edit an unclaimed "
                     "file. Do not describe the fence as enforced in this "
                     "runtime.")
    else:
        lines.append("This runtime HAS hook points.")
        lines.append("")
        lines.append("Configuration: %s" % h["config"])
        lines.append("")
        lines.append("Events: %s." % ", ".join(h["events"]))
        lines.append("")
        lines.append("Verified %s from %s <%s>." % (
            VERIFIED_ON, h["source"][0], h["source"][1]))
        lines.append("")
        lines.append("WHAT THAT DOES NOT MEAN. BrotherMode's hook targets "
                     "(tools/bm_fence_hook.py, and the telemetry hook "
                     "subcommands) parse Claude Code's hook JSON contract, "
                     "documented in docs/HOOKS.md. A runtime that has an event "
                     "with the same NAME is not known to hand that event the "
                     "same JSON, or to read the same decision object back off "
                     "stdout. Nobody has run BrotherMode's hooks against this "
                     "runtime and recorded the payload, so compatibility is "
                     "UNVERIFIED. Wiring them blind risks a gate that fails "
                     "OPEN while looking installed, which is worse than no "
                     "gate, because a fence you believe in is the one you stop "
                     "double checking.")
        lines.append("")
        lines.append("If you want to close that: capture one real payload from "
                     "each event, compare it against docs/HOOKS.md, and write "
                     "the adapter. Until that evidence exists, run the "
                     "commands above by hand and treat the fence as advisory.")
    lines.append("")
    return lines


def render_runtime_file(rt, tools_path):
    """Render one runtime's instruction file. Pure: same inputs, same bytes."""
    L = []
    L.append("<!-- %s. Do not hand edit: regenerate instead. -->" % GENERATED_MARKER)
    L.append("<!-- Runtime: %s -->" % rt["title"])
    for label, url in rt["sources"]:
        L.append("<!-- Convention read %s from %s: %s -->" % (VERIFIED_ON, label, url))
    L.append("")
    L.append("# BrotherMode for %s" % rt["title"])
    L.append("")

    if not rt["verified"]:
        L.append("> STATUS: GENERIC, NOT VERIFIED.")
        L.append(">")
        L.append("> The instruction file convention for this runtime could not "
                 "be confirmed against vendor documentation. Reason: %s"
                 % rt["reason"])
        L.append(">")
        L.append("> Treat the destination below as a guess. Confirm it against "
                 "the runtime's own documentation before relying on this file, "
                 "and do not assume the runtime is reading it.")
        L.append("")

    L.append("## Where this file goes")
    L.append("")
    for d in rt["destinations"]:
        L.append("- %s" % d)
    L.append("")
    L.append("Sources opened on %s:" % VERIFIED_ON)
    L.append("")
    for label, url in rt["sources"]:
        L.append("- %s: <%s>" % (label, url))
    L.append("")

    L.append("## What BrotherMode is")
    L.append("")
    L.append("BrotherMode is a small set of Python tools that keep multi "
             "session and multi agent work honest: one transactional store "
             "records who owns which files, refuses an overlapping claim, and "
             "carries a handover digest so the next session starts from "
             "evidence rather than from memory. It also captures founder "
             "corrections and can retrieve the relevant ones before you act.")
    L.append("")
    L.append("It is standard library Python 3.9. No network, no service, no "
             "API key. Everything below is a local process.")
    L.append("")

    L.append("## The law")
    L.append("")
    L.append("1. ONE WRITER PER FILE. Before editing any file, claim it. If the "
             "store refuses because another record owns it, stop and report "
             "the conflict. Do not edit around a refusal.")
    L.append("2. REPRODUCE BEFORE FIXING. A defect gets a failing test, a hand "
             "run command, or an observed behaviour first. No blind patching.")
    L.append("3. VERIFY AFTER THE LAST EDIT. Any claim that something works "
             "names the command that proved it and quotes the output. A test "
             "that was never shown failing is not evidence.")
    L.append("4. HONEST LIMITS. Anything unverified, sampled, or dropped for "
             "time gets said out loud, not omitted.")
    L.append("5. NEVER PUSH without the founder asking. Commit locally, report "
             "the branch.")
    L.append("")

    L.append("## Commands")
    L.append("")
    L.append("These work in any runtime that can run a shell command, which is "
             "why they carry no per runtime caveat. Run them from the project "
             "root. Paths below are relative to that root.")
    L.append("")
    for mod, purpose, cmds in CLI_SURFACE:
        L.append("`python3 %s/%s <command>` : %s" % (tools_path, mod, purpose))
        L.append("")
        L.append("    commands: %s" % ", ".join(cmds))
        L.append("")
    L.append("FLAGS ARE NOT LISTED HERE ON PURPOSE. Run the command with "
             "`--help` and read the real flags off the tool. An instruction "
             "file that lists flags is an instruction file that teaches a flag "
             "that got renamed six months ago.")
    L.append("")
    L.append("Start of session, every runtime: run the store's `dashboard` and "
             "`verify` to see what is owned and whether the store is healthy. "
             "Before acting on anything the founder has corrected you on "
             "before, run bm_learn.py `lookup` to read the rules without "
             "recording anything, or `apply` when the work is substantial "
             "enough that the retrieval itself should be recorded (it needs a "
             "work identity; run it with `--help` for the exact form).")
    L.append("")

    L.extend(_hook_compat_block(rt))

    if rt["notes"]:
        L.append("## Notes specific to %s" % rt["title"])
        L.append("")
        for n in rt["notes"]:
            L.append("- %s" % n)
        L.append("")

    L.append("## Regenerating")
    L.append("")
    L.append("    python3 %s/bm_runtimes.py emit --runtime %s"
             % (tools_path, rt["key"]))
    L.append("")
    L.append("This file is generated. Edits to it are lost on the next "
             "regeneration. Change the registry in tools/bm_runtimes.py "
             "instead, and change it only with a vendor documentation URL in "
             "hand.")
    L.append("")
    return "\n".join(L)


def render_runtimes_doc(tools_path):
    """Render docs/RUNTIMES.md, the capability table.

    Generated from the SAME registry the files are generated from, and gated:
    test_bm_runtimes.py asserts the file on disk equals this render, so the
    table cannot drift away from what the generator actually emits. A hand
    maintained capability table is a table that lies within a month."""
    L = []
    L.append("<!-- %s. Do not hand edit: regenerate instead. -->" % GENERATED_MARKER)
    L.append("")
    L.append("# Running BrotherMode in other AI coding runtimes")
    L.append("")
    L.append("BrotherMode's engine is standard library Python driven from a "
             "shell. Nothing in it is specific to Claude Code. What is "
             "specific is the WIRING: which file a runtime reads to learn the "
             "law, and whether that runtime can run a program at a lifecycle "
             "event. This page states both, per runtime, with the vendor page "
             "each fact came from and the date it was read.")
    L.append("")
    L.append("Regenerate this page and every adapter file with:")
    L.append("")
    L.append("    python3 %s/bm_runtimes.py emit" % tools_path)
    L.append("")

    L.append("## The two questions, kept apart")
    L.append("")
    L.append("Almost every claim about cross runtime support blurs these, so "
             "they get separate columns:")
    L.append("")
    L.append("- **Hook points**: does the runtime run an external program at "
             "lifecycle events at all. Verified per runtime below.")
    L.append("- **BrotherMode hooks**: do BrotherMode's OWN hook targets work "
             "there. BrotherMode's hooks parse Claude Code's hook JSON "
             "contract (docs/HOOKS.md). A same named event in another runtime "
             "is not known to carry the same payload. Nobody has captured a "
             "real payload from any other runtime, so every non Claude answer "
             "in that column is UNVERIFIED, and UNVERIFIED means do not wire "
             "it: a fence that fails open while looking installed is worse "
             "than no fence.")
    L.append("")
    L.append("Retrieval and the store CLI need no such column. They are "
             "ordinary local processes, so they work in any runtime that can "
             "run a shell command.")
    L.append("")

    L.append("## Capability table")
    L.append("")
    L.append("| Runtime | Instruction file | Store and retrieval CLI | Hook points | BrotherMode hooks |")
    L.append("|---|---|---|---|---|")
    L.append("| Claude Code | CLAUDE.md and SKILL.md (native, see docs/SETUP.md) "
             "| yes | yes | YES, this is the one verified runtime |")
    for rt in RUNTIMES:
        # The registry's own field, NOT a slice of the destination prose. See
        # the install_file note in the registry header for why that matters.
        first_dest = "`%s`" % rt["install_file"]
        if not rt["verified"]:
            first_dest = "%s (GENERIC, unverified)" % first_dest
        if rt["hooks"] is None:
            hp = "none found"
            bh = "not applicable, no hook points"
        else:
            hp = "yes: %s" % ", ".join(rt["hooks"]["events"][:4])
            if len(rt["hooks"]["events"]) > 4:
                hp += ", and %d more" % (len(rt["hooks"]["events"]) - 4)
            bh = "UNVERIFIED, payload shape not captured"
        L.append("| %s | %s | yes | %s | %s |" % (rt["title"], first_dest, hp, bh))
    L.append("")

    L.append("## Per runtime detail")
    L.append("")
    for rt in RUNTIMES:
        L.append("### %s" % rt["title"])
        L.append("")
        if not rt["verified"]:
            L.append("STATUS: GENERIC, NOT VERIFIED. %s" % rt["reason"])
            L.append("")
        L.append("Adapter file: `%s` (emit with `--runtime %s`)"
                 % (rt["staging_name"], rt["key"]))
        L.append("")
        L.append("Install to:")
        L.append("")
        for d in rt["destinations"]:
            L.append("- %s" % d)
        L.append("")
        L.append("Verified %s from:" % VERIFIED_ON)
        L.append("")
        for label, url in rt["sources"]:
            L.append("- %s: <%s>" % (label, url))
        if rt["hooks"] is not None:
            L.append("- %s: <%s>" % (rt["hooks"]["source"][0], rt["hooks"]["source"][1]))
        L.append("")
        if rt["hooks"] is None:
            L.append("Hook points: none found on the page(s) above. The fence "
                     "is advisory in this runtime.")
        else:
            L.append("Hook points: %s" % rt["hooks"]["config"])
            L.append("")
            L.append("Events: %s." % ", ".join(rt["hooks"]["events"]))
        L.append("")
        for n in rt["notes"]:
            L.append("- %s" % n)
        L.append("")

    L.append("## What is deliberately not here")
    L.append("")
    L.append("- No adapter for BrotherMode's hooks in any non Claude runtime. "
             "Writing one without a captured payload would be guessing at a "
             "safety boundary.")
    L.append("- No claim that installing an adapter file makes another runtime "
             "obey the law. An instruction file is persuasion. Only a pre "
             "write hook is enforcement, and only Claude Code has a verified "
             "one today.")
    L.append("- No automatic installation. `emit` writes into a staging "
             "directory and prints where each file goes. AGENTS.md at a "
             "repository root usually already has content in it, and a "
             "generator that overwrote it would be a data loss bug wearing a "
             "convenience feature's clothes.")
    L.append("")
    return "\n".join(L)


# ---------------------------------------------------------------------------
# Writing
# ---------------------------------------------------------------------------
def _write_text(path, text):
    """Write atomically: temp file beside the target, then os.replace. A reader
    (or a second emit) never sees a half written instruction file. THE ONLY
    place this module opens a file for writing."""
    d = os.path.dirname(os.path.abspath(path))
    if d and not os.path.isdir(d):
        os.makedirs(d)
    tmp = path + ".tmp"
    with io.open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    os.replace(tmp, path)


def doc_target(root, out_dir, explicit_out):
    """Where the capability table lives, for BOTH emit and check.

    It used to be hard coded to <root>/docs/RUNTIMES.md in emit and in check,
    which meant --out was a lie: the founder redirected staging to a scratch
    directory and a file OUTSIDE that directory got overwritten anyway. If the
    founder named a directory, everything this command writes goes inside it."""
    if explicit_out:
        return os.path.join(out_dir, "RUNTIMES.md")
    return os.path.join(root, "docs", "RUNTIMES.md")


def is_founder_owned(path):
    """True when a file exists at `path` and was NOT written by this generator.

    The marker line is the first line of everything this module emits. A file
    without it is a file somebody wrote by hand, and this generator will not
    overwrite it. Unreadable is treated as founder owned too: refusing costs a
    regenerate, guessing costs the file."""
    if not os.path.exists(path):
        return False
    try:
        with io.open(path, encoding="utf-8", errors="replace") as f:
            head = f.read(4096)
    except OSError:
        return True
    return GENERATED_MARKER not in head


def _check_registry():
    """Structural refusals that must hold before anything is written. These are
    programming errors in the registry, not user errors, so they raise."""
    keys = [rt["key"] for rt in RUNTIMES]
    if len(set(keys)) != len(keys):
        raise ValueError("duplicate runtime key in the registry: %s" % keys)
    names = [rt["staging_name"] for rt in RUNTIMES]
    if len(set(names)) != len(names):
        raise ValueError("two runtimes emit the same staging filename: %s" % names)
    for rt in RUNTIMES:
        if not rt["sources"]:
            raise ValueError("%s has no source URL" % rt["key"])
        if not rt["verified"] and not rt["reason"]:
            raise ValueError("%s is unverified but states no reason" % rt["key"])
        if rt["verified"] and rt["reason"]:
            raise ValueError("%s is verified but carries an unverified reason"
                             % rt["key"])
        # install_file is what the capability table prints, so it is the field
        # most likely to be read and acted on without reading anything else. It
        # must be a path, and it must be grounded in the destination prose that
        # was read off the vendor page, not typed from memory.
        inst = rt.get("install_file") or ""
        if not inst.strip() or inst != inst.strip():
            raise ValueError("%s has no usable install_file: %r"
                             % (rt["key"], inst))
        if " " in inst:
            raise ValueError("%s install_file is prose, not a path: %r"
                             % (rt["key"], inst))
        dest0 = rt["destinations"][0]
        for part in (os.path.dirname(inst), os.path.basename(inst)):
            if part and part not in dest0:
                raise ValueError(
                    "%s install_file %r is not grounded in its verified "
                    "destination: %r does not appear in %r"
                    % (rt["key"], inst, part, dest0))


def by_key(key):
    for rt in RUNTIMES:
        if rt["key"] == key:
            return rt
    return None


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------
def _parse(argv, known_flags):
    """Refuse unrecognized flags rather than silently treating them as values,
    the same gate bm_threads.py's start command carries. A typo that quietly
    becomes a positional argument is how an unfenced thread shipped once."""
    opts = {}
    rest = []
    i = 0
    while i < len(argv):
        a = argv[i]
        if a.startswith("--"):
            name = a[2:].split("=", 1)[0]
            if name not in known_flags:
                raise ValueError("unrecognized flag: --%s (known: %s)"
                                 % (name, ", ".join(sorted(known_flags))))
            if known_flags[name] == "bool":
                opts[name] = True
                i += 1
                continue
            if "=" in a:
                val = a.split("=", 1)[1]
                i += 1
            else:
                if i + 1 >= len(argv):
                    raise ValueError("flag --%s needs a value" % name)
                val = argv[i + 1]
                i += 2
            if known_flags[name] == "multi":
                opts.setdefault(name, []).append(val)
            else:
                opts[name] = val
            continue
        rest.append(a)
        i += 1
    return opts, rest


def cmd_list(argv):
    opts, rest = _parse(argv, {"json": "bool"})
    if rest:
        raise ValueError("list takes no positional arguments: %s" % rest)
    _check_registry()
    if opts.get("json"):
        rows = []
        for rt in RUNTIMES:
            rows.append({
                "key": rt["key"],
                "title": rt["title"],
                "staging_name": rt["staging_name"],
                "verified": rt["verified"],
                "reason": rt["reason"],
                "sources": [list(s) for s in rt["sources"]],
                "hook_points": rt["hooks"] is not None,
                "hook_events": list(rt["hooks"]["events"]) if rt["hooks"] else [],
                "brothermode_hooks": "unverified" if rt["hooks"] else "not applicable",
            })
        _out(json.dumps({"verified_on": VERIFIED_ON, "runtimes": rows},
                        indent=2, sort_keys=True))
        return 0
    _out("BrotherMode runtime adapters (conventions read %s)" % VERIFIED_ON)
    _out("")
    for rt in RUNTIMES:
        mark = "" if rt["verified"] else "  [GENERIC, UNVERIFIED]"
        _out("  %-14s %s%s" % (rt["key"], rt["title"], mark))
        _out("      file: %s" % rt["staging_name"])
        if rt["hooks"] is None:
            _out("      hook points: none found. Fence is advisory here.")
        else:
            _out("      hook points: yes (%d events). BrotherMode hook "
                 "compatibility UNVERIFIED." % len(rt["hooks"]["events"]))
        _out("      source: %s" % rt["sources"][0][1])
    _out("")
    _out("Store and retrieval commands work in ALL of these: they are ordinary "
         "local processes.")
    return 0


def cmd_emit(argv):
    opts, rest = _parse(argv, {
        "runtime": "multi", "out": "str", "root": "str",
        "dry-run": "bool", "no-doc": "bool",
    })
    if rest:
        raise ValueError("emit takes no positional arguments: %s" % rest)
    _check_registry()

    root, src = resolve_project_root(opts.get("root"))
    if root is None:
        _err("refused: %s" % src)
        return 2

    wanted = opts.get("runtime") or [rt["key"] for rt in RUNTIMES]
    chosen = []
    for k in wanted:
        rt = by_key(k)
        if rt is None:
            _err("refused: unknown runtime %r (known: %s)"
                 % (k, ", ".join(rt2["key"] for rt2 in RUNTIMES)))
            return 2
        chosen.append(rt)

    explicit_out = opts.get("out")
    out_dir = explicit_out or os.path.join(root, DEFAULT_STAGING)
    out_dir = os.path.realpath(os.path.expanduser(out_dir))
    tools_path = tools_reference(root)
    dry = bool(opts.get("dry-run"))

    _out("project root: %s (%s)" % (root, src))
    _out("staging dir:  %s%s" % (out_dir, "  [DRY RUN, nothing written]" if dry else ""))
    _out("")

    # Build the whole plan first, refuse on the whole plan, then write. A per
    # file check would leave a half emitted staging directory behind the moment
    # one target turned out to be founder owned.
    plan = []
    for rt in chosen:
        plan.append((rt, os.path.join(out_dir, rt["staging_name"]),
                     render_runtime_file(rt, tools_path)))

    doc_path = doc_target(root, out_dir, explicit_out)
    write_doc = not opts.get("no-doc") and len(chosen) == len(RUNTIMES)

    guarded = [p for _rt, p, _t in plan]
    if write_doc:
        guarded.append(doc_path)
    owned = [p for p in guarded if is_founder_owned(p)]
    if owned:
        _err("refused: %d target file(s) exist and were not written by this "
             "generator, so they are yours and nothing was written:"
             % len(owned))
        for p in owned:
            _err("  %s" % p)
        _err("Move or delete them, or point --out somewhere else. Every file "
             "this generator owns starts with the line: <!-- %s ... -->"
             % GENERATED_MARKER)
        return 2

    written = []
    for rt, path, text in plan:
        if not dry:
            _write_text(path, text)
        written.append((rt, path))

    if write_doc:
        if not dry:
            _write_text(doc_path, render_runtimes_doc(tools_path))
        _out("capability table: %s" % doc_path)
        _out("")
    elif not opts.get("no-doc"):
        _out("capability table NOT refreshed: it describes every runtime, so it "
             "is only rewritten on a full emit. Run without --runtime to "
             "refresh it.")
        _out("")

    _out("INSTALL MAP. Nothing was copied to the destinations below: these "
         "files are staged, so an existing AGENTS.md or rules file is never "
         "clobbered. The staging directory and the capability table above ARE "
         "written, and only ever over files this generator wrote before.")
    _out("")
    for rt, path in written:
        _out("  %s" % rt["title"])
        _out("    from: %s" % path)
        for d in rt["destinations"]:
            _out("    to:   %s" % d)
        if not rt["verified"]:
            _out("    NOTE: GENERIC and UNVERIFIED. %s" % rt["reason"])
        _out("")
    _out("Hook points are per runtime; BrotherMode's OWN hooks are verified in "
         "Claude Code only. See docs/RUNTIMES.md before wiring any hook.")
    return 0


def cmd_check(argv):
    """Is what is on disk what this generator would emit right now.

    This is the anti drift command, and it is what the suite calls: a generated
    file somebody hand edited, or a registry change nobody regenerated after,
    both show up here as a named stale file rather than as a quiet lie in a
    capability table."""
    opts, rest = _parse(argv, {"out": "str", "root": "str"})
    if rest:
        raise ValueError("check takes no positional arguments: %s" % rest)
    _check_registry()
    root, src = resolve_project_root(opts.get("root"))
    if root is None:
        _err("refused: %s" % src)
        return 2
    explicit_out = opts.get("out")
    out_dir = explicit_out or os.path.join(root, DEFAULT_STAGING)
    out_dir = os.path.realpath(os.path.expanduser(out_dir))
    tools_path = tools_reference(root)

    stale = []
    missing = []
    targets = [(os.path.join(out_dir, rt["staging_name"]),
                render_runtime_file(rt, tools_path)) for rt in RUNTIMES]
    targets.append((doc_target(root, out_dir, explicit_out),
                    render_runtimes_doc(tools_path)))
    for path, expected in targets:
        if not os.path.exists(path):
            missing.append(path)
            continue
        actual = io.open(path, encoding="utf-8").read()
        if actual != expected:
            stale.append(path)
    if missing:
        _out("MISSING (%d):" % len(missing))
        for p in missing:
            _out("  %s" % p)
    if stale:
        _out("STALE (%d), on disk differs from what the registry renders:" % len(stale))
        for p in stale:
            _out("  %s" % p)
    if missing or stale:
        _out("")
        _out("Regenerate: python3 %s/bm_runtimes.py emit" % tools_path)
        return 1
    # Names the path it actually compared rather than a hard coded
    # docs/RUNTIMES.md, which was wrong under --out.
    _out("check OK: %d adapter files and %s match the registry."
         % (len(RUNTIMES), doc_target(root, out_dir, explicit_out)))
    return 0


COMMANDS = {"list": cmd_list, "emit": cmd_emit, "check": cmd_check}


def main(argv):
    if not argv or argv[0] in ("-h", "--help", "help"):
        _out((__doc__ or "").strip())
        _out("")
        _out("commands: %s" % ", ".join(sorted(COMMANDS)))
        return 0 if argv else 2
    fn = COMMANDS.get(argv[0])
    if fn is None:
        _err("unknown command: %s (commands: %s)"
             % (argv[0], ", ".join(sorted(COMMANDS))))
        return 2
    try:
        return fn(argv[1:])
    except ValueError as e:
        _err("refused: %s" % e)
        return 2
    except OSError as e:
        _err("failed: %s" % e)
        return 1


def cli():
    """Console-script entry point for a packaged install (pipx, uv, pip).

    A packaging entry point must be callable with no arguments, and main()
    takes argv. The __main__ block below calls this same function rather
    than repeating the line, so `bm-runtimes` and
    `python3 tools/bm_runtimes.py` cannot drift apart: there is exactly one
    path into main() from a shell."""
    sys.exit(main(sys.argv[1:]))


if __name__ == "__main__":
    cli()
