#!/usr/bin/env python3
"""BrotherMode thread mode: persistent feature threads with a chief command center.

WHY THIS EXISTS
  One session that builds everything fills its context with the detail of every
  feature at once, then compacts, and coordination detail is what gets summarized
  away. Thread mode splits the work the way a small company does: one chief who
  only coordinates (so its context stays small and it almost never compacts), and
  one persistent thread per key feature that keeps its own deep domain context for
  days instead of re-learning the same architecture every morning.

WHY THIS FILE IS THIN (Phase 3 rewire, ratified spec 2026-07-26)
  Every ownership and lifecycle fact a thread has (is it active, who holds it,
  what files does it fence, what did it last say) now lives in exactly ONE place:
  bm_store.py's transactional sqlite store. This module is a CLI wrapper around
  that store, nothing more: it never invents its own notion of "active", it never
  keeps a second copy of a record's state, and it never trusts the working
  directory to mean anything (every command resolves the project root through
  bm_store.resolve_root/require_root, the same one canonical root every other
  BrotherMode tool uses). The V1 shape (two JSON registries, a reusable name as
  identity, a silent takeover on re-claim) is gone, not shimmed: the old
  registry module is deleted, and nothing in this file reads or writes it.

THE CONTRACT (three files per thread, so coordination needs no new infrastructure)
  threads/<name>-<lifecycle8>/STATE.md   the thread's own working plan (human-owned)
  threads/<name>-<lifecycle8>/inbox.md   directives INTO the thread. A VIEW of the
                                         store's directives table; only `send`
                                         regenerates it.
  threads/<name>-<lifecycle8>/outbox.md  advancement OUT of the thread, appended by
                                         `checkpoint`.
  threads/<name>-<lifecycle8>/digest.md  a VIEW of the store's handover digest for
                                         this lifecycle, regenerated by `checkpoint`
                                         (and seeded by `start`).
  The directory name is keyed by LIFECYCLE, not just name (bm_store.thread_dir_name),
  so a name that is reused after a park/adopt can never inherit the previous
  lifecycle's working files.

REVERSIBILITY IS THE POINT (founder requirement, 2026-07-24)
  Thread mode must be switchable OFF mid-project with no chaos and no lost context.
  `off` drains every ACTIVE, PERSISTENT record's handover into the project's root
  STATE.md (tagged by lifecycle and content fingerprint, so a retry can never
  duplicate it) and PARKS it: nothing is deleted, every thread stays resumable via
  `resume`, and the chief continues solo with zero re-exploration.

FAILURE POLICY (matches bm_store.py's two explicit policies)
  Ownership and lifecycle commands (on/off/start/checkpoint/decide/send/park/
  resume/complete/adopt) FAIL CLOSED: a refusal from the store (or from this
  module's own name resolution) is reported and the command exits non-zero.
  Nothing here silently swallows a store refusal into a fake "success". Advisory
  commands (dashboard/recommend) FAIL OPEN: they degrade to a plain message
  rather than raise, because a founder checking status must never be blocked by
  it.

INVARIANTS
  - No network. No subprocess. Pure file I/O plus the store's own sqlite access.
  - Nothing auto-flips: `recommend` only PRINTS advice; only the founder runs
    `on` or `off`.
  - The cap on active persistent records (3) is enforced by the store itself
    (bm_store.MAX_ACTIVE_PERSISTENT), not re-implemented here: one primitive,
    not two copies that can drift apart.
"""
import contextlib
import datetime
import io
import json
import os
import sys
import tempfile
import time
import uuid

_STORE_MOD = None


def _store():
    """Load bm_store.py by path (cached) so this file works from any cwd, the
    same loader shape bm_store.py itself uses for bm_telemetry."""
    global _STORE_MOD
    if _STORE_MOD is None:
        import importlib.util
        here = os.path.dirname(os.path.abspath(__file__))
        spec = importlib.util.spec_from_file_location(
            "bm_store_for_threads", os.path.join(here, "bm_store.py"))
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        _STORE_MOD = mod
    return _STORE_MOD


def _cmd():
    """This tool's own invocation for user-facing instruction text, resolved
    for the layout the reader actually has (repo checkout or packaged
    install). See bm_store.invocation. Falls back to the repo spelling only
    if bm_store cannot be loaded at all, in which case a wrong instruction
    is the least of that session's problems."""
    try:
        return _store().invocation("bm-threads", __file__)
    except Exception:
        return "python3 %s" % os.path.abspath(__file__)


def _refresh_root_view(root):
    """Regenerate the project root's STATE.md after a mutation, calling
    bm_store's own advisory refresh (GATE 4, release-blockers spec,
    2026-07-26). Before this, `off` was the ONLY thread command that ever
    refreshed the root view; every other mutating command here (start,
    checkpoint, decide, send, park, resume, complete, adopt) left an
    active record's lifecycle_uuid missing from STATE.md's generated
    block, so `bm_store.py verify` (run at every SessionStart) reported
    "1 problem(s) found" on every ordinary run after using thread mode,
    even though nothing was actually wrong. Fails open, like every other
    view refresh in this project: the mutation this follows has already
    committed, so a view-refresh failure here is warned, never raised.

    FINDING 12 (external audit 2026-07-27): the refresh runs under the same
    STATE.md lock the handover append takes, so this module can never
    rebuild-and-replace that file while one of its own appends is in flight.
    Losing the lock is warned and skipped, never raised: this is advisory,
    and the next command regenerates the view anyway."""
    bs = _store()
    try:
        with _state_lock(root) as got:
            if not got:
                _warn("bm_threads: another process is holding the STATE.md lock, "
                      "so the generated view was not refreshed after this "
                      "command; the command's own result is still accurate, and "
                      "the next command regenerates the view.")
                return
            bs._refresh_state_view(root)
    except Exception as e:
        _warn("bm_threads: could not refresh the generated STATE.md view "
              "after this command (%r); the command's own result is still "
              "accurate." % (e,))


THREADS_DIRNAME = "threads"
MODE_FILE = "thread-mode.json"          # a mode switch, never ownership (see module doc)
STATE_FILENAME = "STATE.md"

#: Mirrors bm_store.py's own (private) _LEGAL_MOVES graph, so a name-addressed
#: command here resolves to a record in a state the store will actually accept
#: for that move, instead of grabbing the wrong lifecycle when a name has been
#: reused across several lives. If the store's graph ever changes, this must
#: change with it (the store's own transition() is still the enforcement
#: point either way: a stale copy here only makes the ERROR MESSAGE worse,
#: never lets an illegal move through).
_LEGAL_SOURCE_STATES = {
    "parked": ("active",),
    "active": ("parked",),
    "complete": ("active",),
    "adopted": ("active", "parked"),
}


def now():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _default_session_id():
    """A fresh, unguessable session id for THIS process, the exact reasoning
    bm_store._default_cli_session_id documents: two independent invocations
    that both omitted --session must never collide on an empty or shared
    identity, or the second one could silently act as the first's owner.
    A human running a multi-step workflow (start, then later park) must pass
    the SAME --session explicitly across those invocations."""
    return "thread-cli-" + uuid.uuid4().hex


def _parse_kv(argv):
    """"--flag value [value ...]" parsing: everything after a flag, up to the
    next flag, is that flag's value list. The same shape bm_store.py's
    _parse_kv uses, duplicated here on purpose (bm_store.py's own docstring
    says why: a founder who has read one BrotherMode CLI can read the other)."""
    kv, key = {}, None
    for a in argv:
        if a.startswith("--"):
            key = a[2:]
            kv.setdefault(key, [])
        elif key is not None:
            kv[key].append(a)
    return kv


def _reject_unknown_flags(cmd_name, kv, allowed):
    """GATE 5 (release-blockers spec, 2026-07-26): _parse_kv stores ANY
    "--flag" shape without complaint, and every command below used to read
    back only the keys it recognized, silently dropping the rest.
    Reproduced by the orchestrator: `checkpoint X --note "..."` reported
    success and stored nothing (there is no --note flag; the intended
    --files-note was never set). Duplicated from bm_store.py's own
    _reject_unknown_flags on purpose (same reasoning as _parse_kv above)."""
    unknown = sorted(set(kv) - set(allowed))
    if unknown:
        _out("%s: unrecognized flag(s) %s (recognized: %s)"
             % (cmd_name, ", ".join("--" + u for u in unknown),
                ", ".join("--" + a for a in sorted(allowed))))
        sys.exit(2)


def _unrecognized_start_flags(argv_tail, flag_names):
    """GATE 5 helper for `start` specifically: every "--"-shaped token
    anywhere in argv_tail (which spans BOTH the positional-objective region
    and the flag region) that is not one of flag_names. `start` cannot use
    _reject_unknown_flags directly: that helper checks an already-PARSED kv
    dict, but here an unrecognized flag corrupts parsing itself (it never
    bounds the objective, so it is swallowed as prose before any kv exists
    to check). Extracted as its own named function, separate from
    _reject_unknown_flags, so a reinjection test can monkeypatch this exact
    symbol back to a permissive no-op without duplicating cmd_start's
    surrounding objective-splitting logic."""
    return sorted({a for a in argv_tail if a.startswith("--") and a not in flag_names})


# ---------------------------------------------------------------------------
# Root and mode-file I/O. The PROJECT ROOT comes from bm_store.resolve_root,
# never os.getcwd() directly: that is the one anchor every BrotherMode tool
# now shares, and it is what closes the "working directory as identity"
# defect for thread mode's own files too, not only for ownership.
# ---------------------------------------------------------------------------

def _resolve_root():
    return _store().resolve_root()


def _require_root():
    """root, or raises bm_store.OwnershipRefused('no-root', ...) naming the
    exact fix. Every ownership command uses this; advisory commands use
    _resolve_root() instead and degrade instead of raising."""
    return _store().require_root()[0]


def _threads_dir(root):
    return os.path.join(root, THREADS_DIRNAME)


def _mode_path(root):
    return os.path.join(_threads_dir(root), MODE_FILE)


def _atomic_write(path, text):
    """Crash-atomic whole-file replacement (temp file + os.replace), the same
    shape bm_store._atomic_write_text uses. Returns True/False, never raises:
    every caller here is a boundary that must report failure honestly rather
    than let an exception look like a swallowed success."""
    d = os.path.dirname(os.path.abspath(path)) or "."
    try:
        os.makedirs(d, exist_ok=True)
        fd, tmp = tempfile.mkstemp(prefix=".bm_threads.", dir=d)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                f.write(text)
                f.flush()
                os.fsync(f.fileno())
            os.replace(tmp, path)
        except OSError:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise
        return True
    except OSError:
        return False


def _read(path):
    try:
        with io.open(path, encoding="utf-8", errors="replace") as f:
            return f.read()
    except OSError:
        return ""


def _load_mode(root):
    """The mode file: mode ("on"/"off"), since, and a purely descriptive
    history. It holds NOTHING about who owns what work; that question always
    goes to the store. Anything unreadable or malformed reads as an empty,
    OFF mode, so a hand-edited file cannot make every command raise."""
    try:
        d = json.loads(_read(_mode_path(root)) or "{}")
    except Exception:
        return {"mode": "off"}
    if not isinstance(d, dict):
        return {"mode": "off"}
    if d.get("mode") not in ("on", "off"):
        d["mode"] = "off"
    return d


def _save_mode(root, d):
    return _atomic_write(_mode_path(root), json.dumps(d, indent=2, sort_keys=True) + "\n")


def _history(d):
    if not isinstance(d.get("history"), list):
        d["history"] = []
    return d["history"]


# ---------------------------------------------------------------------------
# Output funnel: redact before anything founder-typed (an objective, a
# refusal message quoting a name) reaches stdout. Mirrors bm_store.py's own
# _out/_warn split (fail CLOSED on stdout for ownership text, fail OPEN on
# stderr for advisories) at the scale this smaller CLI actually needs: one
# protected printer plus one pass-through for text a render function already
# protected field-by-field (the dashboard).
# ---------------------------------------------------------------------------

def _protect(s):
    return _store().redact_text(s or "")


def _out(s, end="\n"):
    """THE stdout funnel for founder-influenced text. Refuses (propagates
    RedactionUnavailable to main(), non-zero exit) rather than print anything
    if the redactor cannot be loaded: an ownership-adjacent message must fail
    closed, not print unprotected on the one occasion redaction is broken."""
    sys.stdout.write(_protect(s) + end)
    sys.stdout.flush()


def _out_prerendered(s, end=""):
    """For text a store render function (render_state_md) already redacted
    field by field. Re-running _protect over it would be redundant at best
    and, because that document's own newlines are structure, corrosive at
    worst (mirrors bm_store.py's own _out_prerendered)."""
    sys.stdout.write(s + end)
    sys.stdout.flush()


def _warn(s, end="\n"):
    """THE stderr funnel: advisory, fails OPEN. Degrades to a fixed notice
    instead of raising when the redactor is unavailable, so a broken
    redactor can never silence every warning in the program."""
    bs = _store()
    try:
        safe = _protect(s)
    except bs.RedactionUnavailable:
        sys.stderr.write("bm_threads: WARNING: could not load the redactor; "
                          "a warning was suppressed rather than print unprotected text.\n")
        return
    sys.stderr.write(safe + end)


# ---------------------------------------------------------------------------
# Name resolution: the store's public API works by lifecycle_uuid to keep
# ownership optimistic-concurrency-safe (Decision 3); a thread and a human
# work by NAME. This is the one translation layer, and every command in this
# file goes through it.
#
# IT RESOLVES THROUGH store.identity_by_name(), WHICH READS THE records TABLE
# DIRECTLY, AND NEVER THROUGH store.dump() (FINDING 9, external audit
# 2026-07-27). dump() is a PRESENTATION view: its default-deny redaction
# (GATE C) rewrites records.name along with every other free-text column, so
# a record whose NAME is secret-shaped came back as "[REDACTED]", matched
# the founder's own query against nothing, and became unreachable for the
# rest of its life while its fence stayed claimed. "password=hunter2" and
# "AKIAIOSFODNN7EXAMPLE" are both LEGAL names here (valid_name rejects
# reserved characters, whitespace and non-printable ASCII, nothing else),
# and both trip the redactor, so this was reachable by typing, not only in
# theory. Redaction belongs at the boundary where text LEAVES the machine
# (_out/_protect below), never in the lookup that decides WHICH lifecycle a
# command is talking about.
#
# The same rule is applied to every other record-resolving read in this file
# (_records_by_identity below, used by `off` and `recommend`), because fixing
# only the site the audit named leaves the next one open. Two dump() uses
# remain on purpose and are NOT resolution: `send` renders the directives
# table into inbox.md, and `dashboard` prints render_state_md. Both are
# generated VIEWS, which is exactly where redaction belongs.
# ---------------------------------------------------------------------------

def _find_record(store, name, states=None, lifecycle_prefix=None):
    """The ONE record named `name`, optionally restricted to `states` and/or
    a lifecycle_uuid prefix. Raises OwnershipRefused('not-found') or
    OwnershipRefused('ambiguous-name') rather than guessing.

    MORE THAN ONE CANDIDATE ALWAYS REFUSES (FINDING 10, external audit
    2026-07-27). This function's own docstring already promised it never
    guesses, and it guessed: it sorted by updated_at and returned the newest
    whenever the top two timestamps merely DIFFERED, reporting ambiguity
    only when they were exactly EQUAL. Timestamps are second-resolution
    strings, so in practice they nearly always differ, which made the
    refusal all but unreachable and the silent guess the normal path: `park
    alpha` after a park/adopt/reclaim cycle acted on whichever lifecycle
    happened to be touched most recently, which is not the same question as
    "which one did the founder mean". The refusal names every candidate
    (full lifecycle_uuid plus state, so the founder can act on what they
    read without a `dump` round trip) and the exact flag that resolves it.

    Every name-addressed command inherits this one refusal instead of
    carrying its own copy of the resolution logic: checkpoint, decide and
    send call this directly, park/resume/complete come through
    _transition_cmd, and adopt calls it with the states its transition
    accepts. test_bm.py's TestFinding10AmbiguousNamesAlwaysRefuse asserts
    that both behaviourally and by counting the resolution sites in this
    file."""
    bs = _store()
    matches = store.identity_by_name(name)
    if lifecycle_prefix:
        matches = [r for r in matches if r["lifecycle_uuid"].startswith(lifecycle_prefix)]
    if states:
        matches = [r for r in matches if r["state"] in states]
    if not matches:
        raise bs.OwnershipRefused(
            "not-found",
            "no record named %r%s%s found" % (
                name,
                (" in state(s) %s" % ", ".join(states)) if states else "",
                (" matching lifecycle prefix %r" % lifecycle_prefix) if lifecycle_prefix else ""),
            details={"name": name, "states": states})
    if len(matches) > 1:
        candidates = "; ".join("%s (%s)" % (m["lifecycle_uuid"], m["state"]) for m in matches)
        raise bs.OwnershipRefused(
            "ambiguous-name",
            "%d records are named %r and this command will not guess between "
            "them: %s. Re-run with --lifecycle <prefix> naming the one you "
            "mean (a unique leading portion of its lifecycle uuid above is "
            "enough)." % (len(matches), name, candidates),
            details={"name": name, "candidates": [m["lifecycle_uuid"] for m in matches]})
    return matches[0]


def _records_by_identity(store):
    """Every record in the store as an AUTHORITATIVE bm_store.Record, newest
    first, for the two commands that act on records they did not resolve by
    name (`off` drains every active persistent one, `recommend` counts
    them).

    FINDING 9, the same defect one step removed: both commands used to read
    store.dump() and then make decisions on its rows. state, lifetime,
    session_id and lifecycle_uuid all happen to sit in bm_store's
    _DUMP_SAFE_COLUMNS today, so those two commands worked; records.name did
    NOT, so `off` wrote "[REDACTED]" into the drain heading, and the whole
    arrangement rests on a DISPLAY allowlist staying exactly as it is. One
    column moving out of that allowlist would silently stop `off` from
    finding anything to drain. Decisions are made on rows read straight from
    the records table (store.get), so no display policy can reach them; the
    only field taken from dump() is lifecycle_uuid, the machine-generated
    identity that is never founder text at all.

    Callers still protect the name before it reaches a file or the terminal:
    these rows are authoritative, which means unredacted, exactly like the
    name a founder typed on the command line."""
    out = []
    for row in store.dump()["records"]:
        rec = store.get(row["lifecycle_uuid"])
        if rec is not None:
            out.append(rec)
    out.sort(key=lambda r: (r.updated_at, r.lifecycle_uuid), reverse=True)
    return out


def _thread_dir(root, name, lifecycle_uuid):
    return os.path.join(_threads_dir(root), _store().thread_dir_name(name, lifecycle_uuid))


def _create_if_absent(path, text):
    """CREATE, never overwrite: re-running `start` on a live thread must not
    stamp a blank template over a working plan, chief directives, or an
    advancement history that already exist."""
    if os.path.exists(path):
        return True
    return _atomic_write(path, text)


# ---------------------------------------------------------------------------
# THE STATE.md LOCK (FINDING 12, external audit 2026-07-27). A PARTIAL FIX,
# NAMED AS PARTIAL, because the whole fix does not live in this file.
#
# THE DEFECT: _deliver_handover_once does an UNLOCKED check-then-append on
# the project root STATE.md (read the file, look for the tag, append if it
# is absent), while bm_store.write_state_view independently reads the WHOLE
# file, rebuilds it, and atomically REPLACES it. Interleave read-append with
# read-rebuild-replace and either a handover is ERASED (the replace lands on
# a snapshot taken before the append) or DUPLICATED (two deliveries both
# read a file that has no tag yet, then both append).
#
# THE REAL FIX IS TRANSACTIONAL AND IS NOT IN THIS FILE: handovers belong in
# sqlite and should be GENERATED into the view, so that nothing ever appends
# to a generated file. That needs a handovers table in bm_store.py, which is
# outside this change's fence; the exact follow-up shape is written down in
# _FOLLOWUP_TRANSACTIONAL_HANDOVERS below so it cannot be lost.
#
# WHAT THIS DELIVERS, EXACTLY: every STATE.md mutation THIS MODULE makes
# (the handover append, and the generated-view refreshes this module
# triggers) is serialized behind one lock, and every append is VERIFIED to
# still be on disk before it is reported as delivered. That closes
# bm_threads-against-bm_threads races completely, and turns a
# bm_threads-against-bm_store race from a silent loss into an honest
# failure the caller reports, which leaves the record exactly where it was
# rather than parking a thread whose handover just vanished. It does NOT
# make the two writers atomic with respect to each other: bm_store.py takes
# no lock, and teaching it to would be a change to a file outside the fence.
#
# os.mkdir, not a lock FILE: mkdir is atomic and exclusive on POSIX and on
# Windows (ratified scope, the reason bm_autosave._WorktreeLock uses
# O_CREAT|O_EXCL instead of fcntl.flock), and a directory holds no bytes at
# all, so this lock can never become a place founder text leaks into and
# never adds a write site to this file's reviewed inventory. A lock whose
# holder died is bounded by an age check, the same shape _WorktreeLock uses,
# so a crashed process cannot wedge the CLI forever.
# ---------------------------------------------------------------------------

STATE_LOCK_DIRNAME = "state-md.lock"
STATE_LOCK_WAIT_SECONDS = 10
STATE_LOCK_STALE_SECONDS = 120

#: The follow-up that makes FINDING 12 whole, kept next to the mitigation so
#: the next change to bm_store.py has the shape in front of it:
#:   1. A `handovers` table: (lifecycle_uuid TEXT NOT NULL, fingerprint TEXT
#:      NOT NULL, heading TEXT NOT NULL, body TEXT NOT NULL, delivered_at
#:      TEXT NOT NULL, reason TEXT NOT NULL) with UNIQUE(lifecycle_uuid,
#:      fingerprint). The UNIQUE index IS the dedupe that _handover_tag
#:      currently simulates by scanning a text file for a comment marker.
#:   2. An API `Store.deliver_handover(lifecycle_uuid, version, heading,
#:      reason)` that computes the payload and INSERTs inside the same
#:      transaction as the state change it accompanies (park for `off`,
#:      adopt for `adopt`), so a refused transition can never leave a
#:      delivered handover behind and a crash can never split the two. It
#:      returns "delivered" or "already" from the INSERT result, never from
#:      reading a file, and both columns are stored raw exactly like every
#:      other records/digests column (SECURITY.md already documents the
#:      sqlite file itself as sensitive).
#:   3. render_state_md() grows a "## Handovers" section, rendering every
#:      handovers row through _redacted_view_text() like every other
#:      founder-typed field, INSIDE the BEGIN/END generated markers.
#:      write_state_view then remains the only writer of STATE.md in the
#:      whole project, and this module stops appending entirely:
#:      _deliver_handover_once, _handover_tag, _handover_landed and the lock
#:      below all delete, and the architectural guard test that counts
#:      appenders becomes a guard that there are ZERO.
_FOLLOWUP_TRANSACTIONAL_HANDOVERS = (
    "bm_store.py: handovers table + Store.deliver_handover() inside the "
    "state-change transaction + a rendered section in render_state_md; "
    "then this module's append path and its lock delete entirely.")


class _StateFileLock(object):
    """Serializes this module's writes to the project root STATE.md.
    acquire() returns False rather than raising when the lock cannot be
    taken, so each caller decides its own policy: the handover delivery
    fails CLOSED (the record stays where it is), the advisory view refresh
    fails OPEN (it warns and skips, and the next command regenerates it)."""

    def __init__(self, root, wait=None):
        self.dir = _store().store_dir(root)
        self.path = os.path.join(self.dir, STATE_LOCK_DIRNAME)
        self.wait = STATE_LOCK_WAIT_SECONDS if wait is None else wait
        self.held = False

    def _try_once(self):
        try:
            os.makedirs(self.dir, exist_ok=True)
            os.mkdir(self.path)
        except OSError:
            return False
        return True

    def _clear_if_stale(self):
        try:
            age = time.time() - os.stat(self.path).st_mtime
        except OSError:
            return
        if age > STATE_LOCK_STALE_SECONDS:
            _warn("bm_threads: removing a stale STATE.md lock (%s, %d seconds "
                  "old); the process holding it is gone." % (self.path, int(age)))
            try:
                os.rmdir(self.path)
            except OSError:
                pass

    def acquire(self):
        deadline = time.time() + max(self.wait, 0)
        while True:
            if self._try_once():
                self.held = True
                return True
            self._clear_if_stale()
            if time.time() >= deadline:
                return False
            time.sleep(0.02)

    def release(self):
        if not self.held:
            return
        self.held = False
        try:
            os.rmdir(self.path)
        except OSError:
            pass


@contextlib.contextmanager
def _state_lock(root, wait=None):
    """Yields True when the STATE.md lock is held, False when it could not
    be taken in time, and always releases what it took. NOT reentrant: no
    caller here nests it (the delivery and the view refresh are sequential
    inside every command that does both), and a reentrancy counter would
    hide exactly the kind of nesting that should be noticed."""
    lock = _StateFileLock(root, wait=wait)
    got = lock.acquire()
    try:
        yield got
    finally:
        lock.release()


# ---------------------------------------------------------------------------
# Handover delivery: THE one place text is appended into the project's root
# STATE.md (`off` and `adopt` both call this; nothing else may). Tagged by
# lifecycle_uuid and the store's own 64-hex fingerprint (bm_store fixed F13,
# a 12-char truncated fingerprint colliding two different handovers), so a
# retry after a failure recognises its own earlier delivery instead of
# writing the same handover twice, and a name that is reused across
# lifecycles can never inherit a delivery tag it did not earn.
# ---------------------------------------------------------------------------

def _handover_tag(lifecycle_uuid, fingerprint):
    return "<!-- brothermode-handover:%s:%s -->" % (lifecycle_uuid, fingerprint)


def _handover_landed(state_path, tag):
    """True when `tag` is in STATE.md ON DISK at this moment. Read twice per
    delivery under the lock: once as the idempotence check, and once AFTER
    the append as verification that what was written survived (FINDING 12).
    Its own named function, not an inline `tag in text`, so a reinjection
    test can monkeypatch exactly this symbol back to the old unverified
    shape and prove the calibration."""
    if not os.path.exists(state_path):
        return False
    return tag in _read(state_path)


def _deliver_handover_once(root, store, lifecycle_uuid, heading):
    """Returns "delivered", "already" (idempotent retry, nothing written
    twice), "unavailable" (redaction could not be loaded: refuses, writes
    nothing), "busy" (the STATE.md lock could not be taken: nothing was
    written), "lost" (the append was made but no longer on disk when it was
    checked, so a concurrent writer replaced the file), or False (the file
    write itself failed). Every caller must treat only "delivered"/"already"
    as license to change the record's state; anything else means the record
    must stay exactly where it was, or the handover is lost the moment the
    state moves on.

    The read-check-append-verify sequence runs entirely under the STATE.md
    lock, so two of these can never interleave with each other or with the
    view refreshes this module triggers (see THE STATE.md LOCK above for
    what that does and does not cover)."""
    bs = _store()
    try:
        payload = store.handover_payload(lifecycle_uuid)
        digest_text = store.render_digest(lifecycle_uuid)
    except bs.RedactionUnavailable:
        return "unavailable"
    tag = _handover_tag(lifecycle_uuid, payload["fingerprint"])
    state_path = os.path.join(root, STATE_FILENAME)
    block = "\n%s\n## %s\n%s\n" % (tag, heading, digest_text.strip())
    with _state_lock(root) as got:
        if not got:
            _warn("bm_threads: another process is holding the STATE.md lock "
                  "(%s); no handover was written and nothing was changed. "
                  "Retry when it releases."
                  % os.path.join(_store().store_dir(root), STATE_LOCK_DIRNAME))
            return "busy"
        if _handover_landed(state_path, tag):
            return "already"
        try:
            with io.open(state_path, "a", encoding="utf-8") as f:
                f.write(block)
                f.flush()
                os.fsync(f.fileno())
        except OSError:
            return False
        if not _handover_landed(state_path, tag):
            _warn("bm_threads: the handover for lifecycle %s was appended to %s "
                  "but is no longer there; another writer replaced the file "
                  "underneath this command. Nothing about the record was "
                  "changed, so the handover is still recoverable from the "
                  "store (`dashboard`, or `dump`)." % (lifecycle_uuid, STATE_FILENAME))
            return "lost"
    return "delivered"


#: Why a delivery that was not "delivered"/"already" failed, in the founder's
#: words. One table, so `off` and `adopt` report the same outcome the same
#: way instead of each inventing its own phrasing for the same value.
_HANDOVER_FAILURE_REASONS = {
    False: "the handover write itself failed (permissions or disk)",
    "unavailable": "redaction unavailable",
    "busy": "another process holds the STATE.md lock",
    "lost": "the handover was written but a concurrent writer replaced STATE.md",
}


def _handover_failure_reason(outcome):
    return _HANDOVER_FAILURE_REASONS.get(outcome, "unknown failure (%r)" % (outcome,))


# --------------------------------------------------------------------------
# Commands
# --------------------------------------------------------------------------

def cmd_recommend(argv):
    """Advice ONLY. Never touches the mode file: a surprise mode change
    mid-project is exactly the disruption the founder ruled out."""
    root, _source = _resolve_root()
    mode = _load_mode(root) if root else {"mode": "off"}
    if mode.get("mode") == "on":
        _out("thread mode is already ON. `%s off` drains and parks it." % _cmd())
        return
    n = None
    if argv:
        try:
            n = int(argv[0])
        except ValueError:
            n = None
    if n is None:
        n = 0
        if root is not None:
            try:
                store = _store().Store(root, create=False)
                try:
                    n = sum(1 for r in _records_by_identity(store)
                            if r.state == "active" and r.lifetime == "persistent")
                finally:
                    store.close()
            except Exception:
                n = 0
    if n >= 3:
        _out("RECOMMENDATION: %d parallel features detected or declared. Thread mode "
             "pays off at 3 or more (each thread keeps its own context, the chief "
             "stays small and stops compacting)." % n)
        _out("  turn it on:  %s on" % _cmd())
        _out("  it stays off until you run that. Nothing flips by itself.")
    else:
        _out("RECOMMENDATION: stay single-orchestrator (%d feature(s)). Below 3 "
             "parallel features the per-thread overhead costs more than it saves." % n)


def cmd_on(argv):
    bs = _store()
    root, source = _resolve_root()
    if root is None:
        # Mirrors bm_store.py's own `init`: the one command allowed to
        # proceed with no root, because its job is to create the anchor.
        root = os.path.realpath(os.getcwd())
        source = "cwd (nothing found to anchor on; this becomes the new root)"
    bs.Store(root, create=True).close()  # establishes .brothermode/store.sqlite3
    d = _load_mode(root)
    if d.get("mode") == "on":
        _out("thread mode already ON since %s" % d.get("since", "?"))
        return
    d["mode"] = "on"
    d["since"] = now()
    _history(d).append({"ts": now(), "event": "on"})
    if not _save_mode(root, d):
        raise bs.OwnershipRefused(
            "mode-write-failed",
            "thread-mode.json is not writable; nothing was turned on.")
    _out("thread mode ON. Cap: %d active persistent thread(s) (enforced by the store)."
         % bs.MAX_ACTIVE_PERSISTENT)
    _out("  root resolved via %s" % source)
    _out("  start one:  %s start <feature> \"<objective>\"" % _cmd())
    _out("  review all: %s dashboard" % _cmd())


def cmd_off(argv):
    bs = _store()
    root = _require_root()
    d = _load_mode(root)
    if d.get("mode") != "on":
        _out("thread mode is already OFF.")
        return
    store = bs.Store(root, create=False)
    try:
        # Authoritative rows, never dump()'s presentation view (FINDING 9;
        # see _records_by_identity for why a DISPLAY allowlist must not be
        # what decides which records get drained).
        candidates = [r for r in _records_by_identity(store)
                      if r.state == "active" and r.lifetime == "persistent"]
        if not candidates:
            d["mode"] = "off"
            _history(d).append({"ts": now(), "event": "off", "drained": []})
            if not _save_mode(root, d):
                # _out + sys.exit, not raise: matches every other honest-failure
                # path in this command (below) rather than a one-off exception,
                # so a caller in-process gets the same reporting shape either way.
                _out("MODE FILE NOT UPDATED: no active thread needed draining, "
                     "but thread-mode.json could not be written to OFF.")
                sys.exit(2)
            _out("thread mode OFF (nothing to absorb: no active persistent threads).")
            return
        drained, failed = [], []
        for rec in candidates:
            luid, ver, sid = rec.lifecycle_uuid, rec.version, rec.session_id
            # The authoritative name is founder-typed text, so it is
            # protected ONCE here and only the protected form is used below:
            # the heading goes into STATE.md (exactly like cmd_adopt), and
            # the drained list is both printed and written into
            # thread-mode.json's history. dump() used to redact this field
            # on the way in; reading the real row means this module does it
            # itself, at the boundary where it belongs.
            safe_name = _protect(rec.name)
            outcome = _deliver_handover_once(
                root, store, luid, "Drained from thread mode: %s" % safe_name)
            if outcome not in ("delivered", "already"):
                failed.append((safe_name, luid, _handover_failure_reason(outcome)))
                continue
            try:
                store.transition(luid, ver, "parked", session_id=sid,
                                  note="drained by thread-mode off")
                drained.append(safe_name)
            except (bs.StaleIdentity, bs.OwnershipRefused) as e:
                failed.append((safe_name, luid, str(e)))
        # FINDING 12: under the same lock as the appends above, so this
        # rebuild-and-replace cannot land on a snapshot taken before one of
        # them.
        with _state_lock(root) as got:
            if not got:
                _warn("bm_threads: another process is holding the STATE.md lock, "
                      "so its generated view was not refreshed; every drained "
                      "handover is safely on disk regardless.")
            else:
                try:
                    bs.write_state_view(root)
                except Exception as e:
                    _warn("bm_threads: could not refresh STATE.md's generated view (%r); "
                          "every drained handover is safely on disk regardless." % (e,))
        if failed:
            _out("HANDOVER INCOMPLETE: %d of %d active thread(s) could not be drained:"
                 % (len(failed), len(candidates)))
            for name, luid, reason in failed:
                _out("  - %s (%s): %s" % (name, luid[:8], reason))
            _out("  Thread mode stays ON. %d thread(s) were parked; the rest stay "
                 "ACTIVE so nothing is lost. Fix the issue and run `off` again."
                 % len(drained))
            sys.exit(2)
        d["mode"] = "off"
        _history(d).append({"ts": now(), "event": "off", "drained": drained})
        if not _save_mode(root, d):
            _out("HANDOVER SAFE, MODE FILE NOT UPDATED: %d thread(s) were drained "
                 "and parked, so nothing is lost, but thread-mode.json could not be "
                 "written and still says ON." % len(drained))
            _out("  Fix that file, then run `off` again; re-draining is a no-op "
                 "because every record is already parked.")
            sys.exit(2)
        _out("thread mode OFF (drained and parked %d thread(s), nothing deleted)."
             % len(drained))
        for name in drained:
            _out("    - %s" % name)
        _out("  threads remain on disk under %s/ and are resumable." % THREADS_DIRNAME)
    finally:
        store.close()


def cmd_start(argv):
    bs = _store()
    root = _require_root()
    d = _load_mode(root)
    if d.get("mode") != "on":
        _out("thread mode is OFF. Run `on` first (nothing starts implicitly).")
        sys.exit(2)
    if not argv:
        _out("usage: start <feature-name> \"<objective>\" [--files <path> ...] "
             "[--session SID] [--tier T]")
        sys.exit(2)
    name = argv[0]
    # The objective is POSITIONAL text (V1's ergonomics: no quoting a
    # multi-word objective behind an --objective flag), so it runs from
    # argv[1] up to the first recognised flag; everything from there on is
    # ordinary "--flag value..." parsing via _parse_kv.
    flag_names = ("--files", "--session", "--tier")
    # GATE 5 (release-blockers spec, 2026-07-26): an unrecognized "--xxx"
    # token used to be silently swallowed into the positional objective
    # text, since it never matched flag_names and so never bounded the
    # objective at all -- reproduced with `start X --file f` (singular),
    # which created a thread with NO FENCE at exit 0. Every "--"-shaped
    # token in argv[1:] must be a RECOGNIZED flag before any of it is
    # treated as either objective prose or a flag's value.
    unknown = _unrecognized_start_flags(argv[1:], flag_names)
    if unknown:
        _out("start: unrecognized flag(s) %s (recognized: %s)"
             % (", ".join(unknown), ", ".join(flag_names)))
        sys.exit(2)
    flag_at = min([argv.index(f) for f in flag_names if f in argv[1:]] or [len(argv)])
    objective = " ".join(argv[1:flag_at]).strip() or "(objective not stated)"
    kv = _parse_kv(argv[flag_at:])
    files = kv.get("files", [])
    session_id = " ".join(kv.get("session", [])) or _default_session_id()
    tier = " ".join(kv.get("tier", [])) or "T2"
    store = bs.Store(root, create=False)
    try:
        rec = store.claim(name, "persistent", objective, files or None,
                           session_id=session_id, tier=tier, cwd=os.getcwd())
        digest_text = store.render_digest(rec.lifecycle_uuid)
    finally:
        store.close()
    _refresh_root_view(root)
    base = _thread_dir(root, name, rec.lifecycle_uuid)
    # The CLI-typed name and objective are founder-typed text, and these
    # files are plain views on disk (not a store render function that
    # already redacts internally, the way render_digest does), so they go
    # through the same protect-before-write funnel as everything else this
    # module writes, exactly like the outbox.md line checkpoint appends.
    # valid_name accepts a name shaped like a real secret (bm_store's own
    # round-7 fix note says so explicitly), so the name is never assumed
    # safe just because it passed that check.
    safe_name = _protect(name)
    safe_objective = _protect(objective)
    safe_files = ", ".join(_protect(f) for f in files) if files else "(declare with --files)"
    ok = True
    ok &= _create_if_absent(os.path.join(base, "STATE.md"),
        "# Thread: %s\n\n## Objective\n%s\n\n## Fence (files this thread may write)\n"
        "%s\n\n## Plan and next intent\n- next: (write the next intent BEFORE acting)\n"
        % (safe_name, safe_objective, safe_files))
    ok &= _create_if_absent(os.path.join(base, "inbox.md"),
        "# Inbox for %s\nDirectives from the chief. Regenerated by `send`.\n\n" % safe_name)
    ok &= _create_if_absent(os.path.join(base, "outbox.md"),
        "# Outbox from %s\nAdvancement for the chief. Appended by `checkpoint`.\n\n" % safe_name)
    # A VIEW from minute one (bm_store.render_digest of a record with no
    # checkpoint yet), not a hand-formatted template that could drift from
    # what `checkpoint` regenerates later.
    ok &= _create_if_absent(os.path.join(base, "digest.md"), digest_text)
    if not ok:
        _out("START FAILED: the work record was claimed but this thread's files "
             "could not all be written (permissions or disk).")
        _out("  lifecycle %s stays ACTIVE and fenced; fix the disk issue and use "
             "`park`/`resume` or `adopt` to reconcile it." % rec.lifecycle_uuid)
        sys.exit(2)
    _out("thread '%s' created at %s (lifecycle %s, session %s)"
         % (name, base, rec.lifecycle_uuid, rec.session_id))
    _out("  the thread session should read STATE.md + inbox.md, and write outbox.md "
         "via `checkpoint`")


def cmd_checkpoint(argv):
    bs = _store()
    root = _require_root()
    if not argv:
        _out("usage: checkpoint <thread> [--next TEXT] [--blockers TEXT] "
             "[--files-note TEXT] [--body TEXT] [--topic T] [--decision TEXT] "
             "[--lifecycle PREFIX]")
        sys.exit(2)
    name = argv[0]
    kv = _parse_kv(argv[1:])
    # GATE 5 (release-blockers spec, 2026-07-26): reproduced with
    # `checkpoint X --note "..."`, which reported success and stored
    # nothing -- there is no --note flag (the intended flag is
    # --files-note), and the unrecognized key was silently dropped.
    _reject_unknown_flags("checkpoint", kv,
        ("next", "blockers", "files-note", "body", "topic", "decision", "lifecycle"))
    next_intent = " ".join(kv.get("next", []))
    blockers = " ".join(kv.get("blockers", []))
    files_note = " ".join(kv.get("files-note", []))
    body = " ".join(kv.get("body", []))
    topic = " ".join(kv.get("topic", []))
    decision = " ".join(kv.get("decision", []))
    lifecycle_prefix = " ".join(kv.get("lifecycle", [])) or None
    decisions = [(topic, decision)] if decision else None
    store = bs.Store(root, create=False)
    try:
        rec = _find_record(store, name, states=("active",), lifecycle_prefix=lifecycle_prefix)
        seq = store.checkpoint(rec["lifecycle_uuid"], rec["version"], next_intent,
                                blockers=blockers, files_note=files_note, body=body,
                                decisions=decisions)
        digest_text = store.render_digest(rec["lifecycle_uuid"])
    finally:
        store.close()
    _refresh_root_view(root)
    base = _thread_dir(root, name, rec["lifecycle_uuid"])
    if not _atomic_write(os.path.join(base, "digest.md"), digest_text):
        _warn("bm_threads: checkpoint %d saved in the store, but this thread's "
              "digest.md view could not be refreshed on disk." % seq)
    if next_intent or decision:
        safe_next = _protect(next_intent)
        safe_dec = _protect(decision)
        line = "- %s %s%s\n" % (now()[:16], ("%s | " % safe_dec) if safe_dec else "",
                                 ("next: " + safe_next) if safe_next else "")
        try:
            with io.open(os.path.join(base, "outbox.md"), "a", encoding="utf-8") as f:
                f.write(line)
        except OSError:
            _warn("bm_threads: checkpoint %d saved, but the outbox line for '%s' "
                  "could not be written." % (seq, name))
    _out("checkpoint %d recorded for '%s' (version %s)"
         % (seq, name, rec["version"] + 1))


def cmd_decide(argv):
    bs = _store()
    root = _require_root()
    if not argv:
        _out("usage: decide <thread> --topic T --text TEXT [--lifecycle PREFIX]")
        sys.exit(2)
    name = argv[0]
    kv = _parse_kv(argv[1:])
    _reject_unknown_flags("decide", kv, ("topic", "text", "lifecycle"))
    topic = " ".join(kv.get("topic", []))
    text = " ".join(kv.get("text", []))
    lifecycle_prefix = " ".join(kv.get("lifecycle", [])) or None
    store = bs.Store(root, create=False)
    try:
        rec = _find_record(store, name, lifecycle_prefix=lifecycle_prefix)
        seq = store.decide(rec["lifecycle_uuid"], rec["version"], topic, text)
    finally:
        store.close()
    _refresh_root_view(root)
    _out("decision %d recorded for '%s' (version %s)" % (seq, name, rec["version"] + 1))


def cmd_send(argv):
    """Chief -> thread. inbox.md is fully regenerated from the store's
    directives table (already redacted by dump()'s default-deny), never
    hand-appended: a view can never drift from what it is a view OF."""
    bs = _store()
    root = _require_root()
    if len(argv) < 2:
        _out("usage: send <thread> <message...>")
        sys.exit(2)
    name = argv[0]
    text = " ".join(argv[1:])
    store = bs.Store(root, create=False)
    try:
        rec = _find_record(store, name, states=("active",))
        seq = store.send(rec["lifecycle_uuid"], text)
        data = store.dump()
    finally:
        store.close()
    directives = sorted((r for r in data["directives"]
                          if r["lifecycle_uuid"] == rec["lifecycle_uuid"]),
                         key=lambda r: r["seq"])
    lines = ["- [%s] %s" % (r["created_at"], r["text"]) for r in directives]
    body = ("# Inbox for %s\nDirectives from the chief. Regenerated by `send`.\n\n%s\n"
            % (_protect(name), "\n".join(lines)))
    base = _thread_dir(root, name, rec["lifecycle_uuid"])
    if not _atomic_write(os.path.join(base, "inbox.md"), body):
        _warn("bm_threads: directive %d saved in the store, but inbox.md for '%s' "
              "could not be refreshed on disk." % (seq, name))
    _refresh_root_view(root)
    _out("sent to '%s' (directive %d)" % (name, seq))


def cmd_dashboard(argv):
    """The command center: every record's state on one screen, exactly what
    `off` would drain. render_state_md already redacted every field; print
    it through the pre-rendered path so its own structure survives intact."""
    bs = _store()
    root, source = _resolve_root()
    if root is None:
        _out("BROTHERMODE THREADS  (no project root found here or above)")
        _out("  run `on` to start one, or set BROTHERMODE_ROOT.")
        return
    d = _load_mode(root)
    _out("BROTHERMODE THREADS  mode=%s  cap=%d  root=%s (via %s)"
         % (d.get("mode", "off").upper(), bs.MAX_ACTIVE_PERSISTENT, root, source))
    try:
        _out_prerendered(bs.render_state_md(root), end="")
    except bs.OwnershipRefused as e:
        if e.reason == "no-store":
            # No store to refresh a view against either: refreshing here
            # would just re-hit the same "no-store" refusal inside
            # _refresh_root_view and print a redundant, confusing warning
            # underneath this already-graceful message (a NEW warning this
            # command never used to print). Advisory commands fail open
            # with ONE plain message, not two.
            _out("  no store yet. `on` then `start <feature>` to begin.")
            return
        raise
    except bs.StoreCorrupt as e:
        _out("  STORE CORRUPT: %s" % (e,))
        return
    _refresh_root_view(root)


def _transition_cmd(argv, to_state, usage, needs_evidence=False):
    bs = _store()
    root = _require_root()
    if not argv:
        _out("usage: %s" % usage)
        sys.exit(2)
    name = argv[0]
    kv = _parse_kv(argv[1:])
    _reject_unknown_flags(to_state, kv, ("session", "note", "evidence", "lifecycle"))
    session_id = " ".join(kv.get("session", []))
    note = " ".join(kv.get("note", []))
    evidence = " ".join(kv.get("evidence", []))
    lifecycle_prefix = " ".join(kv.get("lifecycle", [])) or None
    if needs_evidence and not evidence.strip():
        _out("%s: --evidence is required (the check_cmd result)" % to_state)
        sys.exit(2)
    source_states = _LEGAL_SOURCE_STATES.get(to_state)
    store = bs.Store(root, create=False)
    try:
        rec = _find_record(store, name, states=source_states, lifecycle_prefix=lifecycle_prefix)
        result = store.transition(rec["lifecycle_uuid"], rec["version"], to_state,
                                   session_id=session_id, note=note, evidence=evidence)
    finally:
        store.close()
    _refresh_root_view(root)
    _out("%s: '%s' (lifecycle %s) is now %s at version %s"
         % (to_state, name, result.lifecycle_uuid, result.state, result.version))


def cmd_park(argv):
    _transition_cmd(argv, "parked",
                     "park <thread> --session SID [--note TEXT] [--lifecycle PREFIX]")


def cmd_resume(argv):
    _transition_cmd(argv, "active",
                     "resume <thread> --session SID [--note TEXT] [--lifecycle PREFIX]")


def cmd_complete(argv):
    _transition_cmd(argv, "complete",
                     "complete <thread> --session SID --evidence TEXT [--note TEXT] "
                     "[--lifecycle PREFIX]", needs_evidence=True)


def _adopt_core(store, root, rec, session_id, adopt_live, name):
    """The transition-then-deliver core of `adopt` (GATE 3 fix,
    release-blockers spec, 2026-07-26). Extracted as its own named
    function so a reinjection test can monkeypatch this exact symbol back
    to the OLD, broken order (deliver the handover, THEN attempt the
    transition) and prove that a refused adopt used to permanently corrupt
    STATE.md: the OLD code's own docstring claimed "the order IS the
    atomicity: a failure here changes nothing", which was only true for a
    delivery failure, never for a REFUSED transition (e.g.
    live-session-adopt-blocked) -- by then delivery had already landed,
    permanently recording a LIVE thread as "Adopted from dead/stalled
    thread" in STATE.md, and the fingerprint dedupe then suppressed the
    TRUE header when `off` drained the still-active record later
    (reproduced by the orchestrator).

    With the transition first, a refusal changes nothing at all: nothing
    is written into STATE.md until the store has actually recorded the
    adoption. May raise bs.OwnershipRefused('live-session-adopt-blocked')
    from the transition call; the caller (cmd_adopt) turns that into a
    clean CLI refusal. If the transition succeeds but the handover write
    itself then fails, the adoption is real (never rolled back for a
    secondary view write) -- returns the outcome so the caller can report
    that honestly, never as a silent success or a false failure."""
    luid = rec["lifecycle_uuid"]
    result = store.transition(luid, rec["version"], "adopted",
                               session_id=session_id, note="adopted by the chief",
                               adopt_from_live_session=adopt_live)
    # The transition has committed: STATE.md may now be written for it.
    outcome = _deliver_handover_once(root, store, luid,
                                      "Adopted from dead/stalled thread: %s" % _protect(name))
    return outcome, result


def cmd_adopt(argv):
    """A thread died or stalled: the chief ABSORBS its fence and reports,
    rather than silently respawning. See _adopt_core for the GATE 3
    ordering fix this command relies on."""
    bs = _store()
    root = _require_root()
    if not argv:
        _out("usage: adopt <thread> [--session SID] [--adopt-from-live-session] "
             "[--lifecycle PREFIX]")
        sys.exit(2)
    name = argv[0]
    kv = _parse_kv(argv[1:])
    _reject_unknown_flags("adopt", kv, ("session", "adopt-from-live-session", "lifecycle"))
    session_id = " ".join(kv.get("session", [])) or _default_session_id()
    adopt_live = "adopt-from-live-session" in kv
    lifecycle_prefix = " ".join(kv.get("lifecycle", [])) or None
    outcome = result = None
    store = bs.Store(root, create=False)
    try:
        rec = _find_record(store, name, states=_LEGAL_SOURCE_STATES["adopted"],
                            lifecycle_prefix=lifecycle_prefix)
        try:
            outcome, result = _adopt_core(store, root, rec, session_id, adopt_live, name)
        except bs.OwnershipRefused as e:
            if e.reason == "live-session-adopt-blocked":
                _out("ADOPT REFUSED (%s): %s" % (e.reason, e))
                _out("  Re-run with --adopt-from-live-session if you intend to "
                     "displace that session.")
                sys.exit(2)
            raise
        luid = rec["lifecycle_uuid"]
        if outcome not in ("delivered", "already"):
            # One branch, one reason table (_handover_failure_reason), so a
            # NEW outcome value cannot fall through to the "see the warning
            # above" line below with no warning ever printed. FINDING 12
            # added two such values ("busy", "lost").
            _warn("bm_threads: adopted '%s' (lifecycle %s, version %s) in the "
                  "store, but the handover was NOT written into %s: %s. The "
                  "adoption itself is real; the store's digest is intact "
                  "regardless (see `dashboard` or `dump`)."
                  % (name, luid, result.version, STATE_FILENAME,
                     _handover_failure_reason(outcome)))
    finally:
        store.close()
    _refresh_root_view(root)
    if outcome == "already":
        _out("adopted '%s' (resumed): the handover was already in %s from an "
             "earlier attempt, so it was NOT written again." % (name, STATE_FILENAME))
    elif outcome == "delivered":
        _out("adopted '%s': its digest and fence are now in %s (lifecycle %s, "
             "version %s)." % (name, STATE_FILENAME, result.lifecycle_uuid, result.version))
    else:
        _out("adopted '%s' (lifecycle %s, version %s): recorded in the store; "
             "see the warning above about %s." % (name, result.lifecycle_uuid,
                                                   result.version, STATE_FILENAME))
    _out("  DECIDE: respawn the thread, or continue this work solo. Nothing is orphaned.")


_COMMANDS = {
    "recommend": cmd_recommend, "on": cmd_on, "off": cmd_off, "start": cmd_start,
    "checkpoint": cmd_checkpoint, "decide": cmd_decide, "send": cmd_send,
    "dashboard": cmd_dashboard, "park": cmd_park, "resume": cmd_resume,
    "complete": cmd_complete, "adopt": cmd_adopt,
}


def main():
    bs = _store()
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    argv = sys.argv[2:]
    fn = _COMMANDS.get(cmd)
    if fn is None:
        _out_prerendered((__doc__ or "").strip() + "\n")
        _out_prerendered("commands: %s\n" % ", ".join(sorted(_COMMANDS)))
        sys.exit(0 if cmd == "" else 2)
    try:
        fn(argv)
    except SystemExit:
        raise
    except bs.OwnershipRefused as e:
        _out("refused (%s): %s" % (e.reason, e))
        sys.exit(2)
    except bs.StaleIdentity as e:
        _out("refused (stale-identity): %s" % (e,))
        sys.exit(2)
    except bs.StoreCorrupt as e:
        _out("STORE CORRUPT: %s" % (e,))
        sys.exit(1)
    except ValueError as e:
        _out("refused (bad-input): %s" % (e,))
        sys.exit(2)
    sys.exit(0)


if __name__ == "__main__":
    main()
