#!/usr/bin/env python3
"""BrotherMode thread mode: persistent feature threads with a chief command center.

WHY THIS EXISTS
  One session that builds everything fills its context with the detail of every
  feature at once, then compacts, and coordination detail is what gets summarized
  away. Thread mode splits the work the way a small company does: one chief who
  only coordinates (so its context stays small and it almost never compacts), and
  one persistent thread per key feature that keeps its own deep domain context for
  days instead of re-learning the same architecture every morning.

WHY THIS FILE IS THIN (Phase 3 rewire, ratified spec 2026-07-26)
  Every ownership and lifecycle fact a thread has (is it active, who holds it,
  what files does it fence, what did it last say) now lives in exactly ONE place:
  bm_store.py's transactional sqlite store. This module is a CLI wrapper around
  that store, nothing more: it never invents its own notion of "active", it never
  keeps a second copy of a record's state, and it never trusts the working
  directory to mean anything (every command resolves the project root through
  bm_store.resolve_root/require_root, the same one canonical root every other
  BrotherMode tool uses). The V1 shape (two JSON registries, a reusable name as
  identity, a silent takeover on re-claim) is gone, not shimmed: the old
  registry module is deleted, and nothing in this file reads or writes it.

THE CONTRACT (three files per thread, so coordination needs no new infrastructure)
  threads/<name>-<lifecycle8>/STATE.md   the thread's own working plan (human-owned)
  threads/<name>-<lifecycle8>/inbox.md   directives INTO the thread. A VIEW of the
                                         store's directives table; only `send`
                                         regenerates it.
  threads/<name>-<lifecycle8>/outbox.md  advancement OUT of the thread, appended by
                                         `checkpoint`.
  threads/<name>-<lifecycle8>/digest.md  a VIEW of the store's handover digest for
                                         this lifecycle, regenerated by `checkpoint`
                                         (and seeded by `start`).
  The directory name is keyed by LIFECYCLE, not just name (bm_store.thread_dir_name),
  so a name that is reused after a park/adopt can never inherit the previous
  lifecycle's working files.

REVERSIBILITY IS THE POINT (founder requirement, 2026-07-24)
  Thread mode must be switchable OFF mid-project with no chaos and no lost context.
  `off` PARKS every ACTIVE, PERSISTENT record and writes its handover in the SAME
  store transaction (LOOP P12), so the two can never come apart. The project's
  root STATE.md renders the undelivered handovers as generated text; it is a
  view, not the place they live. Nothing is deleted, every thread stays resumable
  via `resume`, and the chief continues solo with zero re-exploration. A retry
  cannot duplicate a handover (UNIQUE on the lifecycle plus the content
  fingerprint), and a refused park writes nothing at all.

FAILURE POLICY (matches bm_store.py's two explicit policies)
  Ownership and lifecycle commands (on/off/start/checkpoint/decide/send/park/
  resume/complete/adopt) FAIL CLOSED: a refusal from the store (or from this
  module's own name resolution) is reported and the command exits non-zero.
  Nothing here silently swallows a store refusal into a fake "success". Advisory
  commands (dashboard/recommend) FAIL OPEN: they degrade to a plain message
  rather than raise, because a founder checking status must never be blocked by
  it.

INVARIANTS
  - No network. No subprocess. Pure file I/O plus the store's own sqlite access.
  - Nothing auto-flips: `recommend` only PRINTS advice; only the founder runs
    `on` or `off`.
  - The cap on active persistent records (3) is enforced by the store itself
    (bm_store.MAX_ACTIVE_PERSISTENT), not re-implemented here: one primitive,
    not two copies that can drift apart.
"""
import contextlib
import datetime
import io
import json
import os
import sys
import tempfile
import time
import uuid

_STORE_MOD = None


def _store():
    """Load bm_store.py by path (cached) so this file works from any cwd, the
    same loader shape bm_store.py itself uses for bm_telemetry."""
    global _STORE_MOD
    if _STORE_MOD is None:
        import importlib.util
        here = os.path.dirname(os.path.abspath(__file__))
        spec = importlib.util.spec_from_file_location(
            "bm_store_for_threads", os.path.join(here, "bm_store.py"))
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        _STORE_MOD = mod
    return _STORE_MOD


def _refresh_root_view(root):
    """Regenerate the project root's STATE.md after a mutation, calling
    bm_store's own advisory refresh (GATE 4, release-blockers spec,
    2026-07-26). Before this, `off` was the ONLY thread command that ever
    refreshed the root view; every other mutating command here (start,
    checkpoint, decide, send, park, resume, complete, adopt) left an
    active record's lifecycle_uuid missing from STATE.md's generated
    block, so `bm_store.py verify` (run at every SessionStart) reported
    "1 problem(s) found" on every ordinary run after using thread mode,
    even though nothing was actually wrong. Fails open, like every other
    view refresh in this project: the mutation this follows has already
    committed, so a view-refresh failure here is warned, never raised.

    LOOP P12 deleted the STATE.md lock this used to take. FINDING 12's lock
    existed to keep THIS module's handover APPEND from interleaving with its
    own view refreshes. There is no append any more: handovers are rows in
    the store, written inside the lifecycle transition, and rendered into
    STATE.md by bm_store.write_state_view, which is now the only writer of
    that file in the whole project. A lock protecting a writer that no longer
    exists is not caution, it is a second thing to keep correct."""
    bs = _store()
    try:
        bs._refresh_state_view(root)
    except Exception as e:
        _warn("bm_threads: could not refresh the generated STATE.md view "
              "after this command (%r); the command's own result is still "
              "accurate." % (e,))


THREADS_DIRNAME = "threads"
MODE_FILE = "thread-mode.json"          # a mode switch, never ownership (see module doc)
STATE_FILENAME = "STATE.md"

#: Mirrors bm_store.py's own (private) _LEGAL_MOVES graph, so a name-addressed
#: command here resolves to a record in a state the store will actually accept
#: for that move, instead of grabbing the wrong lifecycle when a name has been
#: reused across several lives. If the store's graph ever changes, this must
#: change with it (the store's own transition() is still the enforcement
#: point either way: a stale copy here only makes the ERROR MESSAGE worse,
#: never lets an illegal move through).
_LEGAL_SOURCE_STATES = {
    "parked": ("active",),
    "active": ("parked",),
    "complete": ("active",),
    "adopted": ("active", "parked"),
}


def now():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _default_session_id():
    """A fresh, unguessable session id for THIS process, the exact reasoning
    bm_store._default_cli_session_id documents: two independent invocations
    that both omitted --session must never collide on an empty or shared
    identity, or the second one could silently act as the first's owner.
    A human running a multi-step workflow (start, then later park) must pass
    the SAME --session explicitly across those invocations."""
    return "thread-cli-" + uuid.uuid4().hex


def _parse_kv(argv):
    """"--flag value [value ...]" parsing: everything after a flag, up to the
    next flag, is that flag's value list. The same shape bm_store.py's
    _parse_kv uses, duplicated here on purpose (bm_store.py's own docstring
    says why: a founder who has read one BrotherMode CLI can read the other)."""
    kv, key = {}, None
    for a in argv:
        if a.startswith("--"):
            key = a[2:]
            kv.setdefault(key, [])
        elif key is not None:
            kv[key].append(a)
    return kv


def _reject_unknown_flags(cmd_name, kv, allowed):
    """GATE 5 (release-blockers spec, 2026-07-26): _parse_kv stores ANY
    "--flag" shape without complaint, and every command below used to read
    back only the keys it recognized, silently dropping the rest.
    Reproduced by the orchestrator: `checkpoint X --note "..."` reported
    success and stored nothing (there is no --note flag; the intended
    --files-note was never set). Duplicated from bm_store.py's own
    _reject_unknown_flags on purpose (same reasoning as _parse_kv above)."""
    unknown = sorted(set(kv) - set(allowed))
    if unknown:
        _out("%s: unrecognized flag(s) %s (recognized: %s)"
             % (cmd_name, ", ".join("--" + u for u in unknown),
                ", ".join("--" + a for a in sorted(allowed))))
        sys.exit(2)


def _unrecognized_start_flags(argv_tail, flag_names):
    """GATE 5 helper for `start` specifically: every "--"-shaped token
    anywhere in argv_tail (which spans BOTH the positional-objective region
    and the flag region) that is not one of flag_names. `start` cannot use
    _reject_unknown_flags directly: that helper checks an already-PARSED kv
    dict, but here an unrecognized flag corrupts parsing itself (it never
    bounds the objective, so it is swallowed as prose before any kv exists
    to check). Extracted as its own named function, separate from
    _reject_unknown_flags, so a reinjection test can monkeypatch this exact
    symbol back to a permissive no-op without duplicating cmd_start's
    surrounding objective-splitting logic."""
    return sorted({a for a in argv_tail if a.startswith("--") and a not in flag_names})


# ---------------------------------------------------------------------------
# Root and mode-file I/O. The PROJECT ROOT comes from bm_store.resolve_root,
# never os.getcwd() directly: that is the one anchor every BrotherMode tool
# now shares, and it is what closes the "working directory as identity"
# defect for thread mode's own files too, not only for ownership.
# ---------------------------------------------------------------------------

def _resolve_root():
    return _store().resolve_root()


def _require_root():
    """root, or raises bm_store.OwnershipRefused('no-root', ...) naming the
    exact fix. Every ownership command uses this; advisory commands use
    _resolve_root() instead and degrade instead of raising."""
    return _store().require_root()[0]


def _threads_dir(root):
    return os.path.join(root, THREADS_DIRNAME)


def _mode_path(root):
    return os.path.join(_threads_dir(root), MODE_FILE)


def _atomic_write(path, text):
    """Crash-atomic whole-file replacement (temp file + os.replace), the same
    shape bm_store._atomic_write_text uses. Returns True/False, never raises:
    every caller here is a boundary that must report failure honestly rather
    than let an exception look like a swallowed success."""
    d = os.path.dirname(os.path.abspath(path)) or "."
    try:
        os.makedirs(d, exist_ok=True)
        fd, tmp = tempfile.mkstemp(prefix=".bm_threads.", dir=d)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                f.write(text)
                f.flush()
                os.fsync(f.fileno())
            os.replace(tmp, path)
        except OSError:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise
        return True
    except OSError:
        return False


def _read(path):
    try:
        with io.open(path, encoding="utf-8", errors="replace") as f:
            return f.read()
    except OSError:
        return ""


def _load_mode(root):
    """The mode file: mode ("on"/"off"), since, and a purely descriptive
    history. It holds NOTHING about who owns what work; that question always
    goes to the store. Anything unreadable or malformed reads as an empty,
    OFF mode, so a hand-edited file cannot make every command raise."""
    try:
        d = json.loads(_read(_mode_path(root)) or "{}")
    except Exception:
        return {"mode": "off"}
    if not isinstance(d, dict):
        return {"mode": "off"}
    if d.get("mode") not in ("on", "off"):
        d["mode"] = "off"
    return d


def _save_mode(root, d):
    return _atomic_write(_mode_path(root), json.dumps(d, indent=2, sort_keys=True) + "\n")


def _history(d):
    if not isinstance(d.get("history"), list):
        d["history"] = []
    return d["history"]


# ---------------------------------------------------------------------------
# Output funnel: redact before anything founder-typed (an objective, a
# refusal message quoting a name) reaches stdout. Mirrors bm_store.py's own
# _out/_warn split (fail CLOSED on stdout for ownership text, fail OPEN on
# stderr for advisories) at the scale this smaller CLI actually needs: one
# protected printer plus one pass-through for text a render function already
# protected field-by-field (the dashboard).
# ---------------------------------------------------------------------------

def _protect(s):
    return _store().redact_text(s or "")


def _out(s, end="\n"):
    """THE stdout funnel for founder-influenced text. Refuses (propagates
    RedactionUnavailable to main(), non-zero exit) rather than print anything
    if the redactor cannot be loaded: an ownership-adjacent message must fail
    closed, not print unprotected on the one occasion redaction is broken."""
    sys.stdout.write(_protect(s) + end)
    sys.stdout.flush()


def _out_prerendered(s, end=""):
    """For text a store render function (render_state_md) already redacted
    field by field. Re-running _protect over it would be redundant at best
    and, because that document's own newlines are structure, corrosive at
    worst (mirrors bm_store.py's own _out_prerendered)."""
    sys.stdout.write(s + end)
    sys.stdout.flush()


def _warn(s, end="\n"):
    """THE stderr funnel: advisory, fails OPEN. Degrades to a fixed notice
    instead of raising when the redactor is unavailable, so a broken
    redactor can never silence every warning in the program."""
    bs = _store()
    try:
        safe = _protect(s)
    except bs.RedactionUnavailable:
        sys.stderr.write("bm_threads: WARNING: could not load the redactor; "
                          "a warning was suppressed rather than print unprotected text.\n")
        return
    sys.stderr.write(safe + end)


# ---------------------------------------------------------------------------
# Name resolution: the store's public API works by lifecycle_uuid to keep
# ownership optimistic-concurrency-safe (Decision 3); a thread and a human
# work by NAME. This is the one translation layer, and every command in this
# file goes through it.
#
# IT RESOLVES THROUGH store.identity_by_name(), WHICH READS THE records TABLE
# DIRECTLY, AND NEVER THROUGH store.dump() (FINDING 9, external audit
# 2026-07-27). dump() is a PRESENTATION view: its default-deny redaction
# (GATE C) rewrites records.name along with every other free-text column, so
# a record whose NAME is secret-shaped came back as "[REDACTED]", matched
# the founder's own query against nothing, and became unreachable for the
# rest of its life while its fence stayed claimed. "password=hunter2" and
# "AKIAIOSFODNN7EXAMPLE" are both LEGAL names here (valid_name rejects
# reserved characters, whitespace and non-printable ASCII, nothing else),
# and both trip the redactor, so this was reachable by typing, not only in
# theory. Redaction belongs at the boundary where text LEAVES the machine
# (_out/_protect below), never in the lookup that decides WHICH lifecycle a
# command is talking about.
#
# The same rule is applied to every other record-resolving read in this file
# (_records_by_identity below, used by `off` and `recommend`), because fixing
# only the site the audit named leaves the next one open. Two dump() uses
# remain on purpose and are NOT resolution: `send` renders the directives
# table into inbox.md, and `dashboard` prints render_state_md. Both are
# generated VIEWS, which is exactly where redaction belongs.
# ---------------------------------------------------------------------------

def _find_record(store, name, states=None, lifecycle_prefix=None):
    """The ONE record named `name`, optionally restricted to `states` and/or
    a lifecycle_uuid prefix. Raises OwnershipRefused('not-found') or
    OwnershipRefused('ambiguous-name') rather than guessing.

    MORE THAN ONE CANDIDATE ALWAYS REFUSES (FINDING 10, external audit
    2026-07-27). This function's own docstring already promised it never
    guesses, and it guessed: it sorted by updated_at and returned the newest
    whenever the top two timestamps merely DIFFERED, reporting ambiguity
    only when they were exactly EQUAL. Timestamps are second-resolution
    strings, so in practice they nearly always differ, which made the
    refusal all but unreachable and the silent guess the normal path: `park
    alpha` after a park/adopt/reclaim cycle acted on whichever lifecycle
    happened to be touched most recently, which is not the same question as
    "which one did the founder mean". The refusal names every candidate
    (full lifecycle_uuid plus state, so the founder can act on what they
    read without a `dump` round trip) and the exact flag that resolves it.

    Every name-addressed command inherits this one refusal instead of
    carrying its own copy of the resolution logic: checkpoint, decide and
    send call this directly, park/resume/complete come through
    _transition_cmd, and adopt calls it with the states its transition
    accepts. test_bm.py's TestFinding10AmbiguousNamesAlwaysRefuse asserts
    that both behaviourally and by counting the resolution sites in this
    file."""
    bs = _store()
    matches = store.identity_by_name(name)
    if lifecycle_prefix:
        matches = [r for r in matches if r["lifecycle_uuid"].startswith(lifecycle_prefix)]
    if states:
        matches = [r for r in matches if r["state"] in states]
    if not matches:
        raise bs.OwnershipRefused(
            "not-found",
            "no record named %r%s%s found" % (
                name,
                (" in state(s) %s" % ", ".join(states)) if states else "",
                (" matching lifecycle prefix %r" % lifecycle_prefix) if lifecycle_prefix else ""),
            details={"name": name, "states": states})
    if len(matches) > 1:
        candidates = "; ".join("%s (%s)" % (m["lifecycle_uuid"], m["state"]) for m in matches)
        raise bs.OwnershipRefused(
            "ambiguous-name",
            "%d records are named %r and this command will not guess between "
            "them: %s. Re-run with --lifecycle <prefix> naming the one you "
            "mean (a unique leading portion of its lifecycle uuid above is "
            "enough)." % (len(matches), name, candidates),
            details={"name": name, "candidates": [m["lifecycle_uuid"] for m in matches]})
    return matches[0]


def _records_by_identity(store):
    """Every record in the store as an AUTHORITATIVE bm_store.Record, newest
    first, for the two commands that act on records they did not resolve by
    name (`off` drains every active persistent one, `recommend` counts
    them).

    FINDING 9, the same defect one step removed: both commands used to read
    store.dump() and then make decisions on its rows. state, lifetime,
    session_id and lifecycle_uuid all happen to sit in bm_store's
    _DUMP_SAFE_COLUMNS today, so those two commands worked; records.name did
    NOT, so `off` wrote "[REDACTED]" into the drain heading, and the whole
    arrangement rests on a DISPLAY allowlist staying exactly as it is. One
    column moving out of that allowlist would silently stop `off` from
    finding anything to drain. Decisions are made on rows read straight from
    the records table (store.get), so no display policy can reach them; the
    only field taken from dump() is lifecycle_uuid, the machine-generated
    identity that is never founder text at all.

    Callers still protect the name before it reaches a file or the terminal:
    these rows are authoritative, which means unredacted, exactly like the
    name a founder typed on the command line."""
    out = []
    for row in store.dump()["records"]:
        rec = store.get(row["lifecycle_uuid"])
        if rec is not None:
            out.append(rec)
    out.sort(key=lambda r: (r.updated_at, r.lifecycle_uuid), reverse=True)
    return out


def _thread_dir(root, name, lifecycle_uuid):
    return os.path.join(_threads_dir(root), _store().thread_dir_name(name, lifecycle_uuid))


def _create_if_absent(path, text):
    """CREATE, never overwrite: re-running `start` on a live thread must not
    stamp a blank template over a working plan, chief directives, or an
    advancement history that already exist."""
    if os.path.exists(path):
        return True
    return _atomic_write(path, text)


# ---------------------------------------------------------------------------
# WHERE THE HANDOVER APPEND AND ITS LOCK WENT (LOOP P12, 2026-07-29)
#
# THE DEFECT THIS FILE USED TO CARRY: _deliver_handover_once did a
# check-then-append on the project root STATE.md (read the file, look for an
# HTML comment tag, append if it was absent) under this module's own directory
# lock, while bm_store.write_state_view independently read the WHOLE file,
# rebuilt it and atomically REPLACED it, taking no lock at all. Interleave the
# two and either a handover was ERASED (the replace landed on a snapshot taken
# before the append) or DUPLICATED. FINDING 12's lock closed
# bm_threads-against-bm_threads only, and said so; it could not make two
# different modules atomic with respect to each other.
#
# Reproduced against a real store on 2026-07-29, before this change: park the
# record, deliver the handover, let bm_store rewrite STATE.md from a snapshot
# it had already taken, and the record reads 'parked' while the handover text
# is gone from disk with nothing anywhere holding a second copy.
#
# THE FIX IS TRANSACTIONAL AND IT IS NOT IN THIS FILE ANY MORE. A handover is a
# row in bm_store.py's handovers table, INSERTed inside the same sqlite
# transaction as the lifecycle transition that produced it
# (Store.transition(..., handover_heading=...)), and STATE.md renders the
# undelivered ones as generated text. So:
#   - _deliver_handover_once, _handover_tag, _handover_landed,
#     _HANDOVER_FAILURE_REASONS, _handover_failure_reason, _StateFileLock,
#     _state_lock and the three STATE_LOCK_* constants are DELETED, not
#     shimmed. Nothing in this module writes STATE.md at all.
#   - A refused transition can no longer leave a delivered handover behind,
#     because there is no separate delivery step to get ahead of it.
#   - A crash after the commit but before the render costs nothing: the next
#     regeneration renders the row again, because rendering is not delivering.
#   - Retry cannot duplicate: UNIQUE(lifecycle_uuid, payload_fingerprint) is
#     the dedupe that the old comment-marker scan only simulated.
# Handovers that older versions already appended into a STATE.md stay exactly
# where they are, as human prose. Nothing parses them back in; there is no
# marker in those files reliable enough to round-trip (see _migrate_4_to_5).
# ---------------------------------------------------------------------------

# --------------------------------------------------------------------------
# Commands
# --------------------------------------------------------------------------

def cmd_recommend(argv):
    """Advice ONLY. Never touches the mode file: a surprise mode change
    mid-project is exactly the disruption the founder ruled out."""
    root, _source = _resolve_root()
    mode = _load_mode(root) if root else {"mode": "off"}
    if mode.get("mode") == "on":
        _out("thread mode is already ON. `bm_threads.py off` drains and parks it.")
        return
    n = None
    if argv:
        try:
            n = int(argv[0])
        except ValueError:
            n = None
    if n is None:
        n = 0
        if root is not None:
            try:
                store = _store().Store(root, create=False)
                try:
                    n = sum(1 for r in _records_by_identity(store)
                            if r.state == "active" and r.lifetime == "persistent")
                finally:
                    store.close()
            except Exception:
                n = 0
    if n >= 3:
        _out("RECOMMENDATION: %d parallel features detected or declared. Thread mode "
             "pays off at 3 or more (each thread keeps its own context, the chief "
             "stays small and stops compacting)." % n)
        _out("  turn it on:  python3 tools/bm_threads.py on")
        _out("  it stays off until you run that. Nothing flips by itself.")
    else:
        _out("RECOMMENDATION: stay single-orchestrator (%d feature(s)). Below 3 "
             "parallel features the per-thread overhead costs more than it saves." % n)


def cmd_on(argv):
    bs = _store()
    root, source = _resolve_root()
    if root is None:
        # Mirrors bm_store.py's own `init`: the one command allowed to
        # proceed with no root, because its job is to create the anchor.
        root = os.path.realpath(os.getcwd())
        source = "cwd (nothing found to anchor on; this becomes the new root)"
    bs.Store(root, create=True).close()  # establishes .brothermode/store.sqlite3
    d = _load_mode(root)
    if d.get("mode") == "on":
        _out("thread mode already ON since %s" % d.get("since", "?"))
        return
    d["mode"] = "on"
    d["since"] = now()
    _history(d).append({"ts": now(), "event": "on"})
    if not _save_mode(root, d):
        raise bs.OwnershipRefused(
            "mode-write-failed",
            "thread-mode.json is not writable; nothing was turned on.")
    _out("thread mode ON. Cap: %d active persistent thread(s) (enforced by the store)."
         % bs.MAX_ACTIVE_PERSISTENT)
    _out("  root resolved via %s" % source)
    _out("  start one:  python3 tools/bm_threads.py start <feature> \"<objective>\"")
    _out("  review all: python3 tools/bm_threads.py dashboard")


def cmd_off(argv):
    bs = _store()
    root = _require_root()
    d = _load_mode(root)
    if d.get("mode") != "on":
        _out("thread mode is already OFF.")
        return
    store = bs.Store(root, create=False)
    try:
        # Authoritative rows, never dump()'s presentation view (FINDING 9;
        # see _records_by_identity for why a DISPLAY allowlist must not be
        # what decides which records get drained).
        candidates = [r for r in _records_by_identity(store)
                      if r.state == "active" and r.lifetime == "persistent"]
        if not candidates:
            d["mode"] = "off"
            _history(d).append({"ts": now(), "event": "off", "drained": []})
            if not _save_mode(root, d):
                # _out + sys.exit, not raise: matches every other honest-failure
                # path in this command (below) rather than a one-off exception,
                # so a caller in-process gets the same reporting shape either way.
                _out("MODE FILE NOT UPDATED: no active thread needed draining, "
                     "but thread-mode.json could not be written to OFF.")
                sys.exit(2)
            _out("thread mode OFF (nothing to absorb: no active persistent threads).")
            return
        drained, failed = [], []
        for rec in candidates:
            luid, ver, sid = rec.lifecycle_uuid, rec.version, rec.session_id
            # The authoritative name is founder-typed text, so it is
            # protected ONCE here and only the protected form is used below:
            # the heading goes into STATE.md (exactly like cmd_adopt), and
            # the drained list is both printed and written into
            # thread-mode.json's history. dump() used to redact this field
            # on the way in; reading the real row means this module does it
            # itself, at the boundary where it belongs.
            safe_name = _protect(rec.name)
            # LOOP P12: ONE call. The park and its handover are one sqlite
            # transaction, so this loop can no longer produce the two states
            # that used to be reachable here: a record parked with its handover
            # missing (the append lost to a concurrent rewrite), or a handover
            # delivered for a park the store then refused. Whatever this raises,
            # the record is exactly where it was and no handover exists for it.
            try:
                store.transition(
                    luid, ver, "parked", session_id=sid,
                    note="drained by thread-mode off",
                    handover_heading="Drained from thread mode: %s" % safe_name)
                drained.append(safe_name)
            except (bs.StaleIdentity, bs.OwnershipRefused) as e:
                failed.append((safe_name, luid, str(e)))
        # The view is a pure render of what just committed, so a failure here
        # loses nothing: every drained handover is a row in the store, and the
        # next command regenerates the file.
        try:
            bs.write_state_view(root)
        except Exception as e:
            _warn("bm_threads: could not refresh STATE.md's generated view (%r); "
                  "every drained handover is in the store regardless (see "
                  "`python3 tools/bm_store.py handovers`)." % (e,))
        if failed:
            _out("HANDOVER INCOMPLETE: %d of %d active thread(s) could not be drained:"
                 % (len(failed), len(candidates)))
            for name, luid, reason in failed:
                _out("  - %s (%s): %s" % (name, luid[:8], reason))
            _out("  Thread mode stays ON. %d thread(s) were parked; the rest stay "
                 "ACTIVE so nothing is lost. Fix the issue and run `off` again."
                 % len(drained))
            sys.exit(2)
        d["mode"] = "off"
        _history(d).append({"ts": now(), "event": "off", "drained": drained})
        if not _save_mode(root, d):
            _out("HANDOVER SAFE, MODE FILE NOT UPDATED: %d thread(s) were drained "
                 "and parked, so nothing is lost, but thread-mode.json could not be "
                 "written and still says ON." % len(drained))
            _out("  Fix that file, then run `off` again; re-draining is a no-op "
                 "because every record is already parked.")
            sys.exit(2)
        _out("thread mode OFF (drained and parked %d thread(s), nothing deleted)."
             % len(drained))
        for name in drained:
            _out("    - %s" % name)
        _out("  threads remain on disk under %s/ and are resumable." % THREADS_DIRNAME)
    finally:
        store.close()


def cmd_start(argv):
    bs = _store()
    root = _require_root()
    d = _load_mode(root)
    if d.get("mode") != "on":
        _out("thread mode is OFF. Run `on` first (nothing starts implicitly).")
        sys.exit(2)
    if not argv:
        _out("usage: start <feature-name> \"<objective>\" [--files <path> ...] "
             "[--session SID] [--tier T]")
        sys.exit(2)
    name = argv[0]
    # The objective is POSITIONAL text (V1's ergonomics: no quoting a
    # multi-word objective behind an --objective flag), so it runs from
    # argv[1] up to the first recognised flag; everything from there on is
    # ordinary "--flag value..." parsing via _parse_kv.
    flag_names = ("--files", "--session", "--tier")
    # GATE 5 (release-blockers spec, 2026-07-26): an unrecognized "--xxx"
    # token used to be silently swallowed into the positional objective
    # text, since it never matched flag_names and so never bounded the
    # objective at all -- reproduced with `start X --file f` (singular),
    # which created a thread with NO FENCE at exit 0. Every "--"-shaped
    # token in argv[1:] must be a RECOGNIZED flag before any of it is
    # treated as either objective prose or a flag's value.
    unknown = _unrecognized_start_flags(argv[1:], flag_names)
    if unknown:
        _out("start: unrecognized flag(s) %s (recognized: %s)"
             % (", ".join(unknown), ", ".join(flag_names)))
        sys.exit(2)
    flag_at = min([argv.index(f) for f in flag_names if f in argv[1:]] or [len(argv)])
    objective = " ".join(argv[1:flag_at]).strip() or "(objective not stated)"
    kv = _parse_kv(argv[flag_at:])
    files = kv.get("files", [])
    session_id = " ".join(kv.get("session", [])) or _default_session_id()
    tier = " ".join(kv.get("tier", [])) or "T2"
    store = bs.Store(root, create=False)
    try:
        rec = store.claim(name, "persistent", objective, files or None,
                           session_id=session_id, tier=tier, cwd=os.getcwd())
        digest_text = store.render_digest(rec.lifecycle_uuid)
    finally:
        store.close()
    _refresh_root_view(root)
    base = _thread_dir(root, name, rec.lifecycle_uuid)
    # The CLI-typed name and objective are founder-typed text, and these
    # files are plain views on disk (not a store render function that
    # already redacts internally, the way render_digest does), so they go
    # through the same protect-before-write funnel as everything else this
    # module writes, exactly like the outbox.md line checkpoint appends.
    # valid_name accepts a name shaped like a real secret (bm_store's own
    # round-7 fix note says so explicitly), so the name is never assumed
    # safe just because it passed that check.
    safe_name = _protect(name)
    safe_objective = _protect(objective)
    safe_files = ", ".join(_protect(f) for f in files) if files else "(declare with --files)"
    ok = True
    ok &= _create_if_absent(os.path.join(base, "STATE.md"),
        "# Thread: %s\n\n## Objective\n%s\n\n## Fence (files this thread may write)\n"
        "%s\n\n## Plan and next intent\n- next: (write the next intent BEFORE acting)\n"
        % (safe_name, safe_objective, safe_files))
    ok &= _create_if_absent(os.path.join(base, "inbox.md"),
        "# Inbox for %s\nDirectives from the chief. Regenerated by `send`.\n\n" % safe_name)
    ok &= _create_if_absent(os.path.join(base, "outbox.md"),
        "# Outbox from %s\nAdvancement for the chief. Appended by `checkpoint`.\n\n" % safe_name)
    # A VIEW from minute one (bm_store.render_digest of a record with no
    # checkpoint yet), not a hand-formatted template that could drift from
    # what `checkpoint` regenerates later.
    ok &= _create_if_absent(os.path.join(base, "digest.md"), digest_text)
    if not ok:
        _out("START FAILED: the work record was claimed but this thread's files "
             "could not all be written (permissions or disk).")
        _out("  lifecycle %s stays ACTIVE and fenced; fix the disk issue and use "
             "`park`/`resume` or `adopt` to reconcile it." % rec.lifecycle_uuid)
        sys.exit(2)
    _out("thread '%s' created at %s (lifecycle %s, session %s)"
         % (name, base, rec.lifecycle_uuid, rec.session_id))
    _out("  the thread session should read STATE.md + inbox.md, and write outbox.md "
         "via `checkpoint`")


def cmd_checkpoint(argv):
    bs = _store()
    root = _require_root()
    if not argv:
        _out("usage: checkpoint <thread> [--next TEXT] [--blockers TEXT] "
             "[--files-note TEXT] [--body TEXT] [--topic T] [--decision TEXT] "
             "[--lifecycle PREFIX]")
        sys.exit(2)
    name = argv[0]
    kv = _parse_kv(argv[1:])
    # GATE 5 (release-blockers spec, 2026-07-26): reproduced with
    # `checkpoint X --note "..."`, which reported success and stored
    # nothing -- there is no --note flag (the intended flag is
    # --files-note), and the unrecognized key was silently dropped.
    _reject_unknown_flags("checkpoint", kv,
        ("next", "blockers", "files-note", "body", "topic", "decision", "lifecycle"))
    next_intent = " ".join(kv.get("next", []))
    blockers = " ".join(kv.get("blockers", []))
    files_note = " ".join(kv.get("files-note", []))
    body = " ".join(kv.get("body", []))
    topic = " ".join(kv.get("topic", []))
    decision = " ".join(kv.get("decision", []))
    lifecycle_prefix = " ".join(kv.get("lifecycle", [])) or None
    decisions = [(topic, decision)] if decision else None
    store = bs.Store(root, create=False)
    try:
        rec = _find_record(store, name, states=("active",), lifecycle_prefix=lifecycle_prefix)
        seq = store.checkpoint(rec["lifecycle_uuid"], rec["version"], next_intent,
                                blockers=blockers, files_note=files_note, body=body,
                                decisions=decisions)
        digest_text = store.render_digest(rec["lifecycle_uuid"])
    finally:
        store.close()
    _refresh_root_view(root)
    base = _thread_dir(root, name, rec["lifecycle_uuid"])
    if not _atomic_write(os.path.join(base, "digest.md"), digest_text):
        _warn("bm_threads: checkpoint %d saved in the store, but this thread's "
              "digest.md view could not be refreshed on disk." % seq)
    if next_intent or decision:
        safe_next = _protect(next_intent)
        safe_dec = _protect(decision)
        line = "- %s %s%s\n" % (now()[:16], ("%s | " % safe_dec) if safe_dec else "",
                                 ("next: " + safe_next) if safe_next else "")
        try:
            with io.open(os.path.join(base, "outbox.md"), "a", encoding="utf-8") as f:
                f.write(line)
        except OSError:
            _warn("bm_threads: checkpoint %d saved, but the outbox line for '%s' "
                  "could not be written." % (seq, name))
    _out("checkpoint %d recorded for '%s' (version %s)"
         % (seq, name, rec["version"] + 1))


def cmd_decide(argv):
    bs = _store()
    root = _require_root()
    if not argv:
        _out("usage: decide <thread> --topic T --text TEXT [--lifecycle PREFIX]")
        sys.exit(2)
    name = argv[0]
    kv = _parse_kv(argv[1:])
    _reject_unknown_flags("decide", kv, ("topic", "text", "lifecycle"))
    topic = " ".join(kv.get("topic", []))
    text = " ".join(kv.get("text", []))
    lifecycle_prefix = " ".join(kv.get("lifecycle", [])) or None
    store = bs.Store(root, create=False)
    try:
        rec = _find_record(store, name, lifecycle_prefix=lifecycle_prefix)
        seq = store.decide(rec["lifecycle_uuid"], rec["version"], topic, text)
    finally:
        store.close()
    _refresh_root_view(root)
    _out("decision %d recorded for '%s' (version %s)" % (seq, name, rec["version"] + 1))


def cmd_send(argv):
    """Chief -> thread. inbox.md is fully regenerated from the store's
    directives table (already redacted by dump()'s default-deny), never
    hand-appended: a view can never drift from what it is a view OF."""
    bs = _store()
    root = _require_root()
    if len(argv) < 2:
        _out("usage: send <thread> <message...>")
        sys.exit(2)
    name = argv[0]
    text = " ".join(argv[1:])
    store = bs.Store(root, create=False)
    try:
        rec = _find_record(store, name, states=("active",))
        seq = store.send(rec["lifecycle_uuid"], text)
        data = store.dump()
    finally:
        store.close()
    directives = sorted((r for r in data["directives"]
                          if r["lifecycle_uuid"] == rec["lifecycle_uuid"]),
                         key=lambda r: r["seq"])
    lines = ["- [%s] %s" % (r["created_at"], r["text"]) for r in directives]
    body = ("# Inbox for %s\nDirectives from the chief. Regenerated by `send`.\n\n%s\n"
            % (_protect(name), "\n".join(lines)))
    base = _thread_dir(root, name, rec["lifecycle_uuid"])
    if not _atomic_write(os.path.join(base, "inbox.md"), body):
        _warn("bm_threads: directive %d saved in the store, but inbox.md for '%s' "
              "could not be refreshed on disk." % (seq, name))
    _refresh_root_view(root)
    _out("sent to '%s' (directive %d)" % (name, seq))


def cmd_dashboard(argv):
    """The command center: every record's state on one screen, exactly what
    `off` would drain. render_state_md already redacted every field; print
    it through the pre-rendered path so its own structure survives intact."""
    bs = _store()
    root, source = _resolve_root()
    if root is None:
        _out("BROTHERMODE THREADS  (no project root found here or above)")
        _out("  run `on` to start one, or set BROTHERMODE_ROOT.")
        return
    d = _load_mode(root)
    _out("BROTHERMODE THREADS  mode=%s  cap=%d  root=%s (via %s)"
         % (d.get("mode", "off").upper(), bs.MAX_ACTIVE_PERSISTENT, root, source))
    try:
        _out_prerendered(bs.render_state_md(root), end="")
    except bs.OwnershipRefused as e:
        if e.reason == "no-store":
            # No store to refresh a view against either: refreshing here
            # would just re-hit the same "no-store" refusal inside
            # _refresh_root_view and print a redundant, confusing warning
            # underneath this already-graceful message (a NEW warning this
            # command never used to print). Advisory commands fail open
            # with ONE plain message, not two.
            _out("  no store yet. `on` then `start <feature>` to begin.")
            return
        raise
    except bs.StoreCorrupt as e:
        _out("  STORE CORRUPT: %s" % (e,))
        return
    _refresh_root_view(root)


def _transition_cmd(argv, to_state, usage, needs_evidence=False):
    bs = _store()
    root = _require_root()
    if not argv:
        _out("usage: %s" % usage)
        sys.exit(2)
    name = argv[0]
    kv = _parse_kv(argv[1:])
    _reject_unknown_flags(to_state, kv, ("session", "note", "evidence", "lifecycle"))
    session_id = " ".join(kv.get("session", []))
    note = " ".join(kv.get("note", []))
    evidence = " ".join(kv.get("evidence", []))
    lifecycle_prefix = " ".join(kv.get("lifecycle", [])) or None
    if needs_evidence and not evidence.strip():
        _out("%s: --evidence is required (the check_cmd result)" % to_state)
        sys.exit(2)
    source_states = _LEGAL_SOURCE_STATES.get(to_state)
    store = bs.Store(root, create=False)
    try:
        rec = _find_record(store, name, states=source_states, lifecycle_prefix=lifecycle_prefix)
        result = store.transition(rec["lifecycle_uuid"], rec["version"], to_state,
                                   session_id=session_id, note=note, evidence=evidence)
    finally:
        store.close()
    _refresh_root_view(root)
    _out("%s: '%s' (lifecycle %s) is now %s at version %s"
         % (to_state, name, result.lifecycle_uuid, result.state, result.version))


def cmd_park(argv):
    _transition_cmd(argv, "parked",
                     "park <thread> --session SID [--note TEXT] [--lifecycle PREFIX]")


def cmd_resume(argv):
    _transition_cmd(argv, "active",
                     "resume <thread> --session SID [--note TEXT] [--lifecycle PREFIX]")


def cmd_complete(argv):
    _transition_cmd(argv, "complete",
                     "complete <thread> --session SID --evidence TEXT [--note TEXT] "
                     "[--lifecycle PREFIX]", needs_evidence=True)


def _adopt_core(store, root, rec, session_id, adopt_live, name):
    """The whole of `adopt`'s state change, in ONE store transaction.

    GATE 3 (release-blockers spec, 2026-07-26) fixed the ORDER: deliver the
    handover first and a REFUSED transition (live-session-adopt-blocked) had
    already permanently recorded a LIVE thread as "Adopted from dead/stalled
    thread" in STATE.md, and the fingerprint dedupe then suppressed the TRUE
    header when `off` drained the still-active record later. Ordering made that
    much rarer without making it impossible: with the transition first, a crash
    or a failed write between the two still left an adopted record whose
    handover never landed anywhere.

    LOOP P12 removes the "between the two" entirely. handover_heading makes the
    handover row part of the transition's own transaction, so there is no
    second step to fail, to race, or to get ahead of the refusal. A refusal
    writes nothing at all; a success writes both or neither.

    Still its own named function, and still for the reinjection reason: a
    calibration test monkeypatches exactly this symbol back to the old
    two-step shape and proves the defect returns.

    May raise bs.OwnershipRefused('live-session-adopt-blocked'); cmd_adopt
    turns that into a clean CLI refusal."""
    luid = rec["lifecycle_uuid"]
    return store.transition(
        luid, rec["version"], "adopted", session_id=session_id,
        note="adopted by the chief", adopt_from_live_session=adopt_live,
        handover_heading="Adopted from dead/stalled thread: %s" % _protect(name))


def cmd_adopt(argv):
    """A thread died or stalled: the chief ABSORBS its fence and reports,
    rather than silently respawning. See _adopt_core for the transaction that
    makes the adoption and its handover one atomic act."""
    bs = _store()
    root = _require_root()
    if not argv:
        _out("usage: adopt <thread> [--session SID] [--adopt-from-live-session] "
             "[--lifecycle PREFIX]")
        sys.exit(2)
    name = argv[0]
    kv = _parse_kv(argv[1:])
    _reject_unknown_flags("adopt", kv, ("session", "adopt-from-live-session", "lifecycle"))
    session_id = " ".join(kv.get("session", [])) or _default_session_id()
    adopt_live = "adopt-from-live-session" in kv
    lifecycle_prefix = " ".join(kv.get("lifecycle", [])) or None
    result = None
    store = bs.Store(root, create=False)
    try:
        rec = _find_record(store, name, states=_LEGAL_SOURCE_STATES["adopted"],
                            lifecycle_prefix=lifecycle_prefix)
        try:
            result = _adopt_core(store, root, rec, session_id, adopt_live, name)
        except bs.OwnershipRefused as e:
            if e.reason == "live-session-adopt-blocked":
                _out("ADOPT REFUSED (%s): %s" % (e.reason, e))
                _out("  Re-run with --adopt-from-live-session if you intend to "
                     "displace that session.")
                sys.exit(2)
            raise
    finally:
        store.close()
    # A pure render of what already committed. There is no outcome to branch on
    # any more: if the line above returned, the handover is in the store, and
    # this file's only remaining job is to ask for the view to be redrawn.
    _refresh_root_view(root)
    _out("adopted '%s': its digest and fence are recorded, and its handover is "
         "in the store (lifecycle %s, version %s). %s renders it until it is "
         "acknowledged (`python3 tools/bm_store.py handovers`)."
         % (name, result.lifecycle_uuid, result.version, STATE_FILENAME))
    _out("  DECIDE: respawn the thread, or continue this work solo. Nothing is orphaned.")


_COMMANDS = {
    "recommend": cmd_recommend, "on": cmd_on, "off": cmd_off, "start": cmd_start,
    "checkpoint": cmd_checkpoint, "decide": cmd_decide, "send": cmd_send,
    "dashboard": cmd_dashboard, "park": cmd_park, "resume": cmd_resume,
    "complete": cmd_complete, "adopt": cmd_adopt,
}


def main():
    bs = _store()
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    argv = sys.argv[2:]
    fn = _COMMANDS.get(cmd)
    if fn is None:
        _out_prerendered((__doc__ or "").strip() + "\n")
        _out_prerendered("commands: %s\n" % ", ".join(sorted(_COMMANDS)))
        sys.exit(0 if cmd == "" else 2)
    try:
        fn(argv)
    except SystemExit:
        raise
    except bs.OwnershipRefused as e:
        _out("refused (%s): %s" % (e.reason, e))
        sys.exit(2)
    except bs.StaleIdentity as e:
        _out("refused (stale-identity): %s" % (e,))
        sys.exit(2)
    except bs.StoreCorrupt as e:
        _out("STORE CORRUPT: %s" % (e,))
        sys.exit(1)
    except ValueError as e:
        _out("refused (bad-input): %s" % (e,))
        sys.exit(2)
    sys.exit(0)


if __name__ == "__main__":
    main()
